github: stellayazilim
custom:
  - url: "mailto:stellayazilim@example.com"
    type: "licenses/tools"
    description: "Send free software licenses or development tools that can be used to develop Ergosfare."
