using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Stella.Ergosfare.SourceGenerator.Models;
using Stella.Ergosfare.SourceGenerator.Symbols;

namespace Stella.Ergosfare.SourceGenerator;

public sealed partial class ErgosfareRegistrationGenerator
{
    private const string SelectionNamespace = "Stella.Ergosfare.Core.Abstractions.Planning.";
    private readonly record struct SelectionCall(string Caller, string Assembly, string Method);

    private static string? EnclosingMethod(SyntaxNode node, SemanticModel semanticModel, CancellationToken ct)
    {
        for (var symbol = semanticModel.GetEnclosingSymbol(node.SpanStart, ct); symbol is not null; symbol = symbol.ContainingSymbol)
            if (symbol is IMethodSymbol { MethodKind: not (MethodKind.AnonymousFunction or MethodKind.LocalFunction) } method)
                return method.OriginalDefinition.GetDocumentationCommentId();
        return null;
    }

    private static SelectionCall? ReadSelectionCall(GeneratorSyntaxContext ctx, CancellationToken ct)
        => ReadSelectionCall((InvocationExpressionSyntax)ctx.Node, ctx.SemanticModel, ct);

    private static SelectionCall? ReadSelectionCall(InvocationExpressionSyntax node, SemanticModel semanticModel, CancellationToken ct)
    {
        if (semanticModel.GetSymbolInfo(node, ct).Symbol is not IMethodSymbol method) return null;
        method = (method.ReducedFrom ?? method).OriginalDefinition;
        if (method.GetDocumentationCommentId() is not { } id || EnclosingMethod(node, semanticModel, ct) is not { } caller) return null;
        var assembly = method.ContainingAssembly;
        if (!SymbolEqualityComparer.Default.Equals(assembly, semanticModel.Compilation.Assembly)
            && !ReferenceScanner.ReferencesErgosfare(assembly)) return null;
        return new SelectionCall(caller, assembly.Name, id);
    }

    private static void EmitSelectionManifest(SourceProductionContext context,
        ImmutableArray<RegistrationSiteModel> selections, ImmutableArray<SelectionCall> calls)
    {
        var text = new StringBuilder("// <auto-generated/>\n");
        foreach (var site in selections.Distinct())
        {
            if (site.IsOpaque || site.DeclaringMethod is not { } method) continue;
            text.Append("[assembly: global::").Append(SelectionNamespace).Append("GeneratedSelectionAttribute(")
                .Append(Literal(method)).Append(", ").Append(Literal(site.TypeExpression)).Append(", ")
                .Append(site.Module).Append(", ").Append(Literal(site.DiscoveryPattern)).AppendLine(")]");
        }
        foreach (var call in calls.Distinct().OrderBy(c => c.Caller, StringComparer.Ordinal).ThenBy(c => c.Assembly, StringComparer.Ordinal).ThenBy(c => c.Method, StringComparer.Ordinal))
            text.Append("[assembly: global::").Append(SelectionNamespace).Append("GeneratedSelectionCallAttribute(")
                .Append(Literal(call.Caller)).Append(", ").Append(Literal(call.Assembly)).Append(", ")
                .Append(Literal(call.Method)).AppendLine(")]");
        context.AddSource("ErgosfareSelectionManifest.g.cs", SourceText.From(text.ToString(), Encoding.UTF8));
        static string Literal(string? value) => value is null ? "null" : SymbolDisplay.FormatLiteral(value, true);
    }

    private static ImmutableArray<RegistrationSiteModel> ReadReferencedSelections(Compilation compilation, ImmutableArray<SelectionCall> sourceCalls, CancellationToken ct)
    {
        var selections = new Dictionary<(string, string), List<RegistrationSiteModel>>();
        var edges = new Dictionary<(string, string), List<(string, string)>>();
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        foreach (var attribute in assembly.GetAttributes())
        {
            ct.ThrowIfCancellationRequested();
            var name = attribute.AttributeClass?.ToDisplayString();
            var args = attribute.ConstructorArguments;
            if (name == SelectionNamespace + "GeneratedSelectionAttribute" && args.Length == 4 && args[0].Value is string method)
            {
                var key = (assembly.Name, method);
                if (!selections.TryGetValue(key, out var list)) selections.Add(key, list = []);
                list.Add(new RegistrationSiteModel {
                    TypeExpression = args[1].Value as string, TypeMetadataName = null,
                    Module = Convert.ToByte(args[2].Value), DiscoveryPattern = args[3].Value as string,
                    MainHandlerMessageKeys = ImmutableArray<string>.Empty,
                    IsOpaque = false, UnknownTypeLocation = null,
                });
            }
            else if (name == SelectionNamespace + "GeneratedSelectionCallAttribute" && args.Length == 3
                && args[0].Value is string caller && args[1].Value is string targetAssembly && args[2].Value is string targetMethod)
            {
                var key = (assembly.Name, caller);
                if (!edges.TryGetValue(key, out var list)) edges.Add(key, list = []);
                list.Add((targetAssembly, targetMethod));
            }
        }
        // Workspace compilations can reference a project's source before its generated
        // manifest exists. Read those selections with the same semantic readers; metadata
        // references continue to use the exported manifest. Never infer selection merely
        // from a referenced handler's existence.
        var sourceCompilations = new Stack<CompilationReference>(compilation.References.OfType<CompilationReference>());
        var seenCompilations = new HashSet<Compilation>();
        while (sourceCompilations.Count > 0)
        {
            ct.ThrowIfCancellationRequested();
            var source = sourceCompilations.Pop().Compilation;
            if (!seenCompilations.Add(source)) continue;
            foreach (var reference in source.References.OfType<CompilationReference>()) sourceCompilations.Push(reference);
            if (source.Assembly.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() is
                    SelectionNamespace + "GeneratedSelectionAttribute" or SelectionNamespace + "GeneratedSelectionCallAttribute")) continue;
            foreach (var tree in source.SyntaxTrees)
            {
                var model = source.GetSemanticModel(tree);
                foreach (var node in tree.GetRoot(ct).DescendantNodes().OfType<InvocationExpressionSyntax>())
                {
                    ct.ThrowIfCancellationRequested();
                    if (IsRegistrationInvocationCandidate(node) && ReadRegistrationSite(node, model, ct) is { IsOpaque: false } site
                        && EnclosingMethod(node, model, ct) is { } method)
                    {
                        var key = (source.AssemblyName!, method);
                        if (!selections.TryGetValue(key, out var list)) selections.Add(key, list = []);
                        list.Add(site);
                    }
                    if (ReadSelectionCall(node, model, ct) is { } call)
                    {
                        var key = (source.AssemblyName!, call.Caller);
                        if (!edges.TryGetValue(key, out var list)) edges.Add(key, list = []);
                        list.Add((call.Assembly, call.Method));
                    }
                }
            }
        }
        var pending = new Stack<(string, string)>(sourceCalls.Select(c => (c.Assembly, c.Method)));
        var visited = new HashSet<(string, string)>();
        var result = ImmutableArray.CreateBuilder<RegistrationSiteModel>();
        while (pending.Count > 0)
        {
            var key = pending.Pop();
            if (!visited.Add(key)) continue;
            if (selections.TryGetValue(key, out var sites)) result.AddRange(sites);
            if (edges.TryGetValue(key, out var next)) foreach (var edge in next) pending.Push(edge);
        }
        return result.ToImmutable();
    }
}
