using System.Collections.Generic;
using System.Text;
using Stella.Ergosfare.SourceGenerator.Models;

namespace Stella.Ergosfare.SourceGenerator;

/// <summary>
///     Renders the generated registration source. The emitted code is deliberately
///     conservative C# (block namespace, no target-typed constructs) because it compiles
///     inside the consumer's project under whatever language version they use.
/// </summary>
/// <remarks>
///     Types with pre-computed descriptors register through
///     <c>HandlerDescriptors</c> + <c>RegisterDescriptors</c>, bypassing the reflection
///     based descriptor builders entirely; plain messages and open generic types fall back
///     to direct <c>typeof</c>-based <c>Register</c> calls, which also keep the
///     trimmer/AOT analyzers statically satisfied. When the referenced Ergosfare packages
///     predate the descriptor surface, emission degrades to pure <c>Register(Type)</c>
///     calls.
/// </remarks>
internal static class RegistrationEmitter
{
    private const string RegistryFullName = "global::Stella.Ergosfare.Core.Abstractions.Registry.IMessageRegistry";
    private const string DescriptorFullName = "global::Stella.Ergosfare.Core.Abstractions.Registry.Descriptors.IHandlerDescriptor";
    private const string FactoryFullName = "global::Stella.Ergosfare.Core.Abstractions.Registry.Descriptors.HandlerDescriptors";
    private const string CommandBuilderFullName = "global::Stella.Ergosfare.Commands.Extensions.MicrosoftDependencyInjection.CommandModuleBuilder";
    private const string QueryBuilderFullName = "global::Stella.Ergosfare.Queries.Extensions.MicrosoftDependencyInjection.QueryModuleBuilder";
    private const string EventBuilderFullName = "global::Stella.Ergosfare.Events.Extensions.MicrosoftDependencyInjection.EventModuleBuilder";

    /// <summary>
    ///     Emits the <c>ErgosfareGeneratedRegistrations</c> class for the discovered types.
    /// </summary>
    public static string Emit(
        IReadOnlyList<RegistrableTypeModel> types,
        ModuleBuilderAvailability builders,
        string generatorVersion)
    {
        var useDescriptors = builders.HasDescriptorFactory;
        var sb = new StringBuilder(8192);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Stella.Ergosfare.SourceGenerator — do not edit.");
        sb.AppendLine("// Compile-time replacement for reflection-based assembly scanning (RegisterFromAssembly).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Stella.Ergosfare.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Ergosfare constructs (messages, handlers, interceptors) declared in this assembly,");
        sb.AppendLine("    ///     discovered at compile time. Handler descriptors are pre-computed, so registration");
        sb.AppendLine("    ///     performs no reflection over handler types; plain messages and open generic types");
        sb.AppendLine("    ///     register through the runtime fallback. Trimmed/AOT builds stay warning-free:");
        sb.AppendLine("    ///     every type is referenced statically via <c>typeof</c>.");
        sb.AppendLine("    /// </summary>");
        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"Stella.Ergosfare.SourceGenerator\", \"")
          .Append(generatorVersion)
          .AppendLine("\")]");
        sb.AppendLine("    internal static class ErgosfareGeneratedRegistrations");
        sb.AppendLine("    {");

        var wroteMember = false;

        if (builders.HasMessageRegistry)
        {
            EmitRegisterAll(sb, ref wroteMember, types, useDescriptors);
        }

        if (builders.HasCommandModuleBuilder)
        {
            EmitBuilderExtension(sb, ref wroteMember, CommandBuilderFullName, "command", "CreateCommandDescriptors",
                Filter(types, static t => t.IsCommand), useDescriptors && builders.CommandBuilderHasRegisterDescriptors);
        }

        if (builders.HasQueryModuleBuilder)
        {
            EmitBuilderExtension(sb, ref wroteMember, QueryBuilderFullName, "query", "CreateQueryDescriptors",
                Filter(types, static t => t.IsQuery), useDescriptors && builders.QueryBuilderHasRegisterDescriptors);
        }

        if (builders.HasEventModuleBuilder)
        {
            EmitBuilderExtension(sb, ref wroteMember, EventBuilderFullName, "event", "CreateEventDescriptors",
                Filter(types, static t => t.IsEvent), useDescriptors && builders.EventBuilderHasRegisterDescriptors);
        }

        if (builders.HasMessageRegistry && useDescriptors && HasDescriptors(types))
        {
            EmitDescriptorFactory(sb, ref wroteMember, "CreateDescriptors", types);
        }

        if (builders.HasCommandModuleBuilder && useDescriptors && builders.CommandBuilderHasRegisterDescriptors)
        {
            EmitDescriptorFactoryIfAny(sb, ref wroteMember, "CreateCommandDescriptors", Filter(types, static t => t.IsCommand));
        }

        if (builders.HasQueryModuleBuilder && useDescriptors && builders.QueryBuilderHasRegisterDescriptors)
        {
            EmitDescriptorFactoryIfAny(sb, ref wroteMember, "CreateQueryDescriptors", Filter(types, static t => t.IsQuery));
        }

        if (builders.HasEventModuleBuilder && useDescriptors && builders.EventBuilderHasRegisterDescriptors)
        {
            EmitDescriptorFactoryIfAny(sb, ref wroteMember, "CreateEventDescriptors", Filter(types, static t => t.IsEvent));
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static List<RegistrableTypeModel> Filter(
        IReadOnlyList<RegistrableTypeModel> types,
        System.Func<RegistrableTypeModel, bool> predicate)
    {
        var filtered = new List<RegistrableTypeModel>(types.Count);

        foreach (var type in types)
        {
            if (predicate(type))
            {
                filtered.Add(type);
            }
        }

        return filtered;
    }

    private static bool HasDescriptors(IReadOnlyList<RegistrableTypeModel> types)
    {
        foreach (var type in types)
        {
            if (type.Descriptors.Length > 0)
            {
                return true;
            }
        }

        return false;
    }

    private static void EmitRegisterAll(
        StringBuilder sb,
        ref bool wroteMember,
        IReadOnlyList<RegistrableTypeModel> types,
        bool useDescriptors)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     Registers every Ergosfare construct declared in this assembly into the given");
        sb.AppendLine("        ///     registry, regardless of module.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static void RegisterAll(").Append(RegistryFullName).AppendLine(" registry)");
        sb.AppendLine("        {");

        if (useDescriptors && HasDescriptors(types))
        {
            sb.AppendLine("            registry.RegisterDescriptors(CreateDescriptors());");
        }

        foreach (var type in types)
        {
            if (!useDescriptors || type.Descriptors.Length == 0)
            {
                sb.Append("            registry.Register(typeof(").Append(type.TypeofExpression).AppendLine("));");
            }
        }

        sb.AppendLine("        }");
    }

    private static void EmitBuilderExtension(
        StringBuilder sb,
        ref bool wroteMember,
        string builderFullName,
        string moduleName,
        string factoryMethodName,
        List<RegistrableTypeModel> moduleTypes,
        bool useDescriptors)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.Append("        ///     Registers every ").Append(moduleName).AppendLine("-module construct declared in this");
        sb.AppendLine("        ///     assembly. Drop-in replacement for <c>RegisterFromAssembly</c>.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static ").Append(builderFullName).AppendLine(" RegisterGenerated(");
        sb.Append("            this ").Append(builderFullName).AppendLine(" builder)");
        sb.AppendLine("        {");

        if (useDescriptors && HasDescriptors(moduleTypes))
        {
            sb.Append("            builder.RegisterDescriptors(").Append(factoryMethodName).AppendLine("());");
        }

        foreach (var type in moduleTypes)
        {
            if (!useDescriptors || type.Descriptors.Length == 0)
            {
                sb.Append("            builder.Register(typeof(").Append(type.TypeofExpression).AppendLine("));");
            }
        }

        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
    }

    private static void EmitDescriptorFactoryIfAny(
        StringBuilder sb,
        ref bool wroteMember,
        string methodName,
        List<RegistrableTypeModel> types)
    {
        if (HasDescriptors(types))
        {
            EmitDescriptorFactory(sb, ref wroteMember, methodName, types);
        }
    }

    private static void EmitDescriptorFactory(
        StringBuilder sb,
        ref bool wroteMember,
        string methodName,
        IReadOnlyList<RegistrableTypeModel> types)
    {
        StartMember(sb, ref wroteMember);
        sb.Append("        private static ").Append(DescriptorFullName).Append("[] ").Append(methodName).AppendLine("()");
        sb.Append("            => new ").Append(DescriptorFullName).AppendLine("[]");
        sb.AppendLine("            {");

        foreach (var type in types)
        {
            foreach (var descriptor in type.Descriptors)
            {
                EmitDescriptorEntry(sb, type, descriptor);
            }
        }

        sb.AppendLine("            };");
    }

    private static void EmitDescriptorEntry(StringBuilder sb, in RegistrableTypeModel type, in DescriptorModel descriptor)
    {
        var factoryMethod = descriptor.Kind switch
        {
            DescriptorKind.MainHandler => "Handler",
            DescriptorKind.PreInterceptor => "PreInterceptor",
            DescriptorKind.PostInterceptor => "PostInterceptor",
            DescriptorKind.ExceptionInterceptor => "ExceptionInterceptor",
            DescriptorKind.FinalInterceptor => "FinalInterceptor",
            _ => "Handler",
        };

        sb.Append("                ").Append(FactoryFullName).Append('.').Append(factoryMethod)
          .Append("(typeof(").Append(descriptor.MessageTypeExpression).Append(')');

        if (descriptor.ResultTypeExpression is not null)
        {
            sb.Append(", typeof(").Append(descriptor.ResultTypeExpression).Append(')');
        }

        sb.Append(", typeof(").Append(type.TypeofExpression).Append(')');

        // Weight and groups are trailing optional parameters; emit them only when they
        // deviate from the factory defaults (weight 0, default group).
        if (type.Weight != 0 || type.GroupsExpression is not null)
        {
            sb.Append(", ").Append(type.Weight).Append('u');
        }

        if (type.GroupsExpression is not null)
        {
            sb.Append(", ").Append(type.GroupsExpression);
        }

        sb.AppendLine("),");
    }

    private static void StartMember(StringBuilder sb, ref bool wroteMember)
    {
        if (wroteMember)
        {
            sb.AppendLine();
        }

        wroteMember = true;
    }
}
