
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Stella.Ergosfare.SourceGenerator.Models;

namespace Stella.Ergosfare.SourceGenerator;

/// <summary>
///     Renders the generated registration source. The emitted code is deliberately
///     conservative C# (block namespace, no target-typed constructs) because it compiles
///     inside the consumer's project under whatever language version they use.
/// </summary>
/// <remarks>
///     Every registration surface comes in two overloads: the pattern-less form selects
///     default discovery (types without a <c>[DiscoveryKey]</c>), while the pattern form
///     cherry-picks keyed types (<c>RegisterGenerated("reporting.*")</c>). Types are
///     emitted in clusters sharing the same discovery-key set, each guarded by a key-match
///     check; selection is a union, so overlapping selections across chained calls are
///     safe. Registration names constructs, nothing more — what each one's pipeline looks
///     like was decided at compile time and lives in the frozen composition table. Messages
///     go through <c>Register(typeof(T))</c>; pipeline participants are batched into one
///     <c>RegisterParticipants</c> call. Every type is named through <c>typeof</c>, which
///     also keeps the trimmer/AOT analyzers statically satisfied.
/// </remarks>
internal static class RegistrationEmitter
{
    private const string CatalogFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchRoots.FrozenCompositionCatalog";
    private const string CommandBuilderFullName = "global::Stella.Ergosfare.Commands.Extensions.MicrosoftDependencyInjection.CommandModuleBuilder";
    private const string QueryBuilderFullName = "global::Stella.Ergosfare.Queries.Extensions.MicrosoftDependencyInjection.QueryModuleBuilder";
    private const string EventBuilderFullName = "global::Stella.Ergosfare.Events.Extensions.MicrosoftDependencyInjection.EventModuleBuilder";
    private const string DispatchRootsFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchRoots.GeneratedDispatchRoots";
    private const string DispatchSiteAttributeFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchSites.DispatchSiteAttribute";
    private const string DispatchManifestAttributeFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchSites.DispatchManifestAttribute";
    private const string ManualRegistrationAttributeFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchSites.ManualRegistrationAttribute";
    private const string DispatchKindFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchSites.DispatchKind";

    /// <summary>
    ///     The dispatch-manifest schema version stamped into the assembly marker.
    /// </summary>
    private const int DispatchManifestVersion = 1;

    /// <summary>
    ///     Emits the <c>ErgosfareGeneratedRegistrations</c> class for the discovered types.
    /// </summary>
    public static string Emit(
        IReadOnlyList<RegistrableTypeModel> types,
        ModuleBuilderAvailability builders,
        IReadOnlyList<VoidPlanModel> voidPlans,
        IReadOnlyList<ResultPlanModel> resultPlans,
        IReadOnlyList<StagedPlanModel> stagedPlans,
        IReadOnlyList<FrozenCompositionModel> frozenCompositions,
        IReadOnlyList<DispatchSiteModel> dispatchSites,
        IReadOnlyList<RegistrationSiteModel> registrationSites,
        bool emitDispatchManifest,
        string generatorVersion)
    {
        var emitDispatchRoots = builders.HasDispatchRoots && HasDispatchableMessages(types);
        var sb = new StringBuilder(8192);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Stella.Ergosfare.SourceGenerator — do not edit.");
        sb.AppendLine("// Compile-time registration of the discovered Ergosfare constructs — no reflection-based assembly scanning.");
        // Annotations on, warnings off. The annotation context has to be enabled because
        // the emitted code writes `T?` where a contract declares it. The warning context
        // must not be: this file lands in someone else's compilation, under their nullable
        // settings and possibly their TreatWarningsAsErrors, and every nullability warning
        // it could raise would be about code they cannot edit. The generic-argument
        // positions are where this bites — a handler whose result is a nullable reference
        // type (`IQueryHandler<Q, TodoDto?>`) does not satisfy a constraint written against
        // the unannotated type, and CS8631 would fail the consumer's build.
        sb.AppendLine("#nullable enable annotations");
        sb.AppendLine("#nullable disable warnings");
        // Registration references every discovered construct, including ones the user has
        // deprecated; surfacing their [Obsolete] here would warn on code nobody wrote.
        sb.AppendLine("#pragma warning disable CS0612, CS0618");
        sb.AppendLine();

        if (emitDispatchManifest)
        {
            EmitDispatchManifest(sb, dispatchSites, registrationSites);
        }

        sb.AppendLine("namespace Stella.Ergosfare.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Ergosfare constructs (messages, handlers, interceptors) discovered at compile");
        sb.AppendLine("    ///     time in this compilation and its scanned references. Handler descriptors are");
        sb.AppendLine("    ///     pre-computed, so registration performs no reflection over handler types; plain");
        sb.AppendLine("    ///     messages and open generic types register through the runtime fallback.");
        sb.AppendLine("    ///     Trimmed/AOT builds stay warning-free: every type is referenced statically via");
        sb.AppendLine("    ///     <c>typeof</c>.");
        sb.AppendLine("    /// </summary>");
        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"Stella.Ergosfare.SourceGenerator\", \"")
          .Append(generatorVersion)
          .AppendLine("\")]");
        sb.AppendLine("    internal static class ErgosfareGeneratedRegistrations");
        sb.AppendLine("    {");

        var wroteMember = false;

        if (builders.HasCompositionCatalog)
        {
            EmitCatalogSurface(sb, ref wroteMember, types, emitDispatchRoots);
        }

        if (builders.HasCommandModuleBuilder)
        {
            EmitBuilderSurface(sb, ref wroteMember, CommandBuilderFullName, "command",
                Filter(types, static t => t.IsCommand), builders.CommandBuilderHasRegisterParticipants,
                emitDispatchRoots);
        }

        if (builders.HasQueryModuleBuilder)
        {
            EmitBuilderSurface(sb, ref wroteMember, QueryBuilderFullName, "query",
                Filter(types, static t => t.IsQuery), builders.QueryBuilderHasRegisterParticipants,
                emitDispatchRoots);
        }

        if (builders.HasEventModuleBuilder)
        {
            EmitBuilderSurface(sb, ref wroteMember, EventBuilderFullName, "event",
                Filter(types, static t => t.IsEvent), builders.EventBuilderHasRegisterParticipants,
                emitDispatchRoots);
        }

        if (emitDispatchRoots)
        {
            EmitDispatchRoots(sb, ref wroteMember, types, voidPlans, resultPlans, stagedPlans,
                builders.DispatchRootsHasPlanFactories,
                builders.DispatchRootsHasProviderPlanFactories,
                builders.HasKeyedServiceExtensions);

            EmitStagedPlanClasses(sb, ref wroteMember, stagedPlans, builders.StagedPlansSupportDirectConstruction);
        }

        // Independent of the dispatch-root gate above: that one asks whether this
        // compilation declares a message worth rooting generics for, while the table
        // answers what serves a message — including the abstract bases a dispatched
        // subtype resolves through, which are never rooted themselves.
        if (builders.HasDispatchRoots)
        {
            EmitFrozenCompositions(sb, ref wroteMember, frozenCompositions);
        }

        EmitMatchesHelper(sb, ref wroteMember);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    ///     Emits the assembly-level dispatch manifest: the marker attribute (present even
    ///     with zero sites — it distinguishes "dispatches nothing" from "unknown", and
    ///     carries the opaque-registration flag), one <c>DispatchSite</c> attribute per
    ///     distinct (message type, surface, opacity) the compilation's own source
    ///     dispatches, and one <c>ManualRegistration</c> attribute per provably registered
    ///     type. Referenced assemblies' manifest entries are never re-exported; each
    ///     assembly records only what it does itself.
    /// </summary>
    private static void EmitDispatchManifest(
        StringBuilder sb,
        IReadOnlyList<DispatchSiteModel> dispatchSites,
        IReadOnlyList<RegistrationSiteModel> registrationSites)
    {
        var hasOpaqueRegistrations = false;

        foreach (var registration in registrationSites)
        {
            if (registration.IsOpaque)
            {
                hasOpaqueRegistrations = true;
                break;
            }
        }

        sb.Append("[assembly: ").Append(DispatchManifestAttributeFullName)
          .Append('(').Append(DispatchManifestVersion);

        if (hasOpaqueRegistrations)
        {
            sb.Append(", HasOpaqueRegistrations = true");
        }

        sb.AppendLine(")]");

        if (dispatchSites.Count > 0)
        {
            var entries = new List<(string MetadataName, DispatchSiteKind Kind, bool Opaque, string GroupKey, ImmutableArray<string> Groups)>(dispatchSites.Count);
            var seen = new HashSet<(string, DispatchSiteKind, bool, string)>();

            foreach (var site in dispatchSites)
            {
                // A site whose filter could not be read carries no group payload: the
                // reading assembly must not mistake "unreadable" for "the default group".
                var groups = site.HasUnprovableGroups ? ImmutableArray<string>.Empty : site.Groups;
                var entry = (site.MessageTypeMetadataName, site.Kind, site.IsOpaque, GroupKey: JoinGroups(groups));

                if (seen.Add(entry))
                {
                    entries.Add((entry.MessageTypeMetadataName, entry.Kind, entry.IsOpaque, entry.GroupKey, groups));
                }
            }

            // Deterministic output regardless of invocation order.
            entries.Sort(static (x, y) =>
            {
                var byName = string.CompareOrdinal(x.MetadataName, y.MetadataName);

                if (byName != 0)
                {
                    return byName;
                }

                var byGroups = string.CompareOrdinal(x.GroupKey, y.GroupKey);

                if (byGroups != 0)
                {
                    return byGroups;
                }

                var byKind = x.Kind.CompareTo(y.Kind);

                return byKind != 0 ? byKind : x.Opaque.CompareTo(y.Opaque);
            });

            foreach (var (metadataName, kind, opaque, _, groups) in entries)
            {
                sb.Append("[assembly: ").Append(DispatchSiteAttributeFullName).Append('(')
                  .Append(SymbolDisplay.FormatLiteral(metadataName, quote: true)).Append(", ")
                  .Append(DispatchKindFullName).Append('.').Append(DispatchKindMemberName(kind)).Append(", ")
                  .Append(opaque ? "true" : "false");

                if (!groups.IsEmpty)
                {
                    sb.Append(", Groups = new string[] { ");

                    for (var i = 0; i < groups.Length; i++)
                    {
                        sb.Append(i == 0 ? string.Empty : ", ")
                          .Append(SymbolDisplay.FormatLiteral(groups[i], quote: true));
                    }

                    sb.Append(" }");
                }

                sb.AppendLine(")]");
            }
        }

        if (registrationSites.Count > 0)
        {
            var registeredNames = new List<string>(registrationSites.Count);
            var seenNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (var registration in registrationSites)
            {
                if (registration.TypeMetadataName is { } name && seenNames.Add(name))
                {
                    registeredNames.Add(name);
                }
            }

            registeredNames.Sort(StringComparer.Ordinal);

            foreach (var name in registeredNames)
            {
                sb.Append("[assembly: ").Append(ManualRegistrationAttributeFullName).Append('(')
                  .Append(SymbolDisplay.FormatLiteral(name, quote: true)).AppendLine(")]");
            }
        }

        sb.AppendLine();
    }

    /// <summary>
    ///     Flattens a normalized group set into one comparable string — deduplication and
    ///     sorting already happened, so joining is enough to make two spellings of one set
    ///     compare equal.
    /// </summary>
    private static string JoinGroups(ImmutableArray<string> groups)
    {
        if (groups.IsEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();

        for (var i = 0; i < groups.Length; i++)
        {
            // The unit separator keeps {"ab"} and {"a","b"} distinct; a group name
            // carrying a control character is not a name anyone writes.
            sb.Append(i == 0 ? string.Empty : "").Append(groups[i]);
        }

        return sb.ToString();
    }

    private static string DispatchKindMemberName(DispatchSiteKind kind)
        => kind switch
        {
            DispatchSiteKind.Command => "Command",
            DispatchSiteKind.Query => "Query",
            DispatchSiteKind.Stream => "Stream",
            DispatchSiteKind.Event => "Event",
            _ => "Message",
        };

    private static List<RegistrableTypeModel> Filter(
        IReadOnlyList<RegistrableTypeModel> types,
        Func<RegistrableTypeModel, bool> predicate)
    {
        var filtered = new List<RegistrableTypeModel>(types.Count);

        foreach (var type in types)
        {
            if (predicate(type))
            {
                filtered.Add(type);
            }
        }

        return filtered;
    }

    /// <summary>
    ///     Whether any modeled type is a pipeline participant rather than a plain message —
    ///     the compile-time descriptors are what identify one.
    /// </summary>
    private static bool HasParticipants(IReadOnlyList<RegistrableTypeModel> types)
    {
        foreach (var type in types)
        {
            if (type.Descriptors.Length > 0)
            {
                return true;
            }
        }

        return false;
    }

    private static bool HasDispatchableMessages(IReadOnlyList<RegistrableTypeModel> types)
    {
        foreach (var type in types)
        {
            if (type.IsDispatchableMessage)
            {
                return true;
            }
        }

        return false;
    }

    private static void EmitCatalogSurface(
        StringBuilder sb,
        ref bool wroteMember,
        IReadOnlyList<RegistrableTypeModel> types,
        bool emitDispatchRoots)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     Selects every discovered construct that participates in default discovery");
        sb.AppendLine("        ///     (no <c>[DiscoveryKey]</c>) into the given catalog, regardless of module.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static void RegisterAll(").Append(CatalogFullName).AppendLine(" compositions)");
        sb.AppendLine("        {");
        sb.AppendLine("            RegisterAll(compositions, \"\");");
        sb.AppendLine("        }");

        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     Selects every discovered construct whose discovery keys match the given");
        sb.AppendLine("        ///     pattern — an exact key or a trailing-<c>*</c> prefix glob — regardless of");
        sb.AppendLine("        ///     module. Chained calls with overlapping patterns are safe: selection is a");
        sb.AppendLine("        ///     union.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static void RegisterAll(").Append(CatalogFullName).AppendLine(" compositions, string discoveryKeyPattern)");
        sb.AppendLine("        {");

        if (emitDispatchRoots)
        {
            sb.AppendLine("            RootDispatchInstantiations();");
            sb.AppendLine();
        }

        EmitKeyedBody(sb, types, batchParticipants: false, receiver: "compositions", registerMethod: "Select");
        sb.AppendLine("        }");
    }

    private static void EmitBuilderSurface(
        StringBuilder sb,
        ref bool wroteMember,
        string builderFullName,
        string moduleName,
        List<RegistrableTypeModel> moduleTypes,
        bool batchParticipants,
        bool emitDispatchRoots)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.Append("        ///     Registers every discovered ").Append(moduleName).AppendLine("-module construct that participates");
        sb.AppendLine("        ///     in default discovery (no <c>[DiscoveryKey]</c>) — the bulk collection path.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static ").Append(builderFullName).AppendLine(" RegisterGenerated(");
        sb.Append("            this ").Append(builderFullName).AppendLine(" builder)");
        sb.AppendLine("        {");
        sb.AppendLine("            return RegisterGenerated(builder, \"\");");
        sb.AppendLine("        }");

        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.Append("        ///     Registers every discovered ").Append(moduleName).AppendLine("-module construct whose discovery");
        sb.AppendLine("        ///     keys match the given pattern — an exact key or a trailing-<c>*</c> prefix");
        sb.AppendLine("        ///     glob. Chain calls to compose selections; overlapping patterns are safe.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static ").Append(builderFullName).AppendLine(" RegisterGenerated(");
        sb.Append("            this ").Append(builderFullName).AppendLine(" builder, string discoveryKeyPattern)");
        sb.AppendLine("        {");

        if (emitDispatchRoots)
        {
            sb.AppendLine("            RootDispatchInstantiations();");
            sb.AppendLine();
        }

        EmitKeyedBody(sb, moduleTypes, batchParticipants, receiver: "builder", registerMethod: "Register");
        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
    }

    /// <summary>
    ///     Emits the dispatch-root method: one <c>AddMessage</c> per dispatchable message
    ///     plus <c>AddResult</c>/<c>AddStream</c> per closed result contract. The generic
    ///     closures let the runtime's dispatch caches construct their executors and
    ///     invokers without <c>MakeGenericType</c> and give Native AOT a static anchor for
    ///     every instantiation. Additions are idempotent, so every registration surface
    ///     calls this unconditionally.
    /// </summary>
    private static void EmitDispatchRoots(
        StringBuilder sb,
        ref bool wroteMember,
        IReadOnlyList<RegistrableTypeModel> types,
        IReadOnlyList<VoidPlanModel> voidPlans,
        IReadOnlyList<ResultPlanModel> resultPlans,
        IReadOnlyList<StagedPlanModel> stagedPlans,
        bool emitPlanFactories,
        bool emitProviderPlanFactories,
        bool hasKeyedServiceExtensions)
    {
        StartMember(sb, ref wroteMember);
        // A module initializer, not a registration side effect: the dispatch roots and the
        // compiled plans are properties of the compilation — like the frozen compositions —
        // so they enter the process-wide tables the moment the assembly loads. A container
        // that never calls RegisterGenerated()/RegisterAll() still dispatches through the
        // plans compiled here; which rows it runs is settled by what it registered. The
        // registration surfaces keep their explicit calls — every Add below is idempotent.
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void RootDispatchInstantiations()");
        sb.AppendLine("        {");

        foreach (var type in types)
        {
            if (!type.IsDispatchableMessage)
            {
                continue;
            }

            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(".AddMessage<").Append(type.TypeofExpression).AppendLine(">();");

            foreach (var result in type.DispatchResults)
            {
                sb.Append("            ").Append(DispatchRootsFullName)
                  .Append(result.IsStream ? ".AddStream<" : ".AddResult<")
                  .Append(type.TypeofExpression).Append(", ").Append(result.ResultTypeExpression)
                  .AppendLine(">();");
            }
        }

        // Compile-time pipeline plans: the runtime re-validates each one against the
        // registry per version, so a plan can only lose its speedup, never change
        // behavior. Qualifying handlers additionally carry a construction factory —
        // parameterless `new` or a provider-taking one for dependency-injected
        // constructors — which the runtime uses only after verifying the handler's
        // effective DI registration is the module's own plain transient one.
        foreach (var plan in voidPlans)
        {
            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(".AddVoidPlan<").Append(plan.MessageTypeExpression)
              .Append(", ").Append(plan.HandlerTypeExpression)
              .Append(">(");

            AppendPlanFactory(sb, plan.HandlerTypeExpression, plan.HasDirectConstruction,
                plan.ProviderConstructionExpression, plan.UsesKeyedServices,
                emitPlanFactories, emitProviderPlanFactories, hasKeyedServiceExtensions);

            sb.AppendLine(");");
        }

        foreach (var plan in resultPlans)
        {
            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(".AddResultPlan<").Append(plan.MessageTypeExpression)
              .Append(", ").Append(plan.ResultTypeExpression)
              .Append(", ").Append(plan.HandlerTypeExpression)
              .Append(">(");

            AppendPlanFactory(sb, plan.HandlerTypeExpression, plan.HasDirectConstruction,
                plan.ProviderConstructionExpression, plan.UsesKeyedServices,
                emitPlanFactories, emitProviderPlanFactories, hasKeyedServiceExtensions);

            sb.AppendLine(");");
        }

        // Staged plans: bespoke straight-line pipelines for interceptor-bearing messages,
        // emitted as sealed plan classes below. Advisory like every plan — the hosting
        // executor re-validates the baked composition per registry version.
        for (var i = 0; i < stagedPlans.Count; i++)
        {
            var plan = stagedPlans[i];

            // A broadcast roots into its own store: a publish looks there and a send looks at
            // the resultless plans, so which store answered settles the delivery difference
            // and no dispatch has to branch on the message.
            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(plan.IsBroadcast ? ".AddBroadcastPlan<" : ".AddStagedPlan<")
              .Append(plan.MessageTypeExpression);

            if (plan.ResultTypeExpression is not null)
            {
                sb.Append(", ").Append(plan.ResultTypeExpression);
            }

            sb.Append(">(new StagedPlan").Append(i).Append("()");

            // The group set is part of the key, so it travels with the plan. The default
            // set is the absent argument — the overload without it.
            if (!plan.Groups.IsEmpty)
            {
                sb.Append(", new string[] { ");

                for (var g = 0; g < plan.Groups.Length; g++)
                {
                    sb.Append(g == 0 ? string.Empty : ", ")
                      .Append(SymbolDisplay.FormatLiteral(plan.Groups[g], quote: true));
                }

                sb.Append(" }");
            }

            sb.AppendLine(");");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    ///     Emits the module initializer that appends this assembly's frozen compositions to
    ///     the process-wide table. A composition is a property of the compilation, not of
    ///     any registration call: a container that never calls <c>RegisterGenerated()</c>
    ///     still dispatches the messages compiled here, and a plugin assembly contributes
    ///     its table the moment it loads. Which of the rows a given container runs is
    ///     settled separately, by what that container registered.
    /// </summary>
    private static void EmitFrozenCompositions(
        StringBuilder sb, ref bool wroteMember, IReadOnlyList<FrozenCompositionModel> frozenCompositions)
    {
        if (frozenCompositions.Count == 0)
        {
            return;
        }

        StartMember(sb, ref wroteMember);
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void PopulateFrozenCompositions()");
        sb.AppendLine("        {");

        foreach (var composition in frozenCompositions)
        {
            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(".AddFrozenComposition(new ").Append(FrozenCompositionFullName).AppendLine("(");
            sb.Append("                typeof(").Append(composition.MessageTypeExpression).AppendLine("),");
            AppendFrozenSegment(sb, composition.Handlers);
            AppendFrozenSegment(sb, composition.IndirectHandlers);
            AppendFrozenSegment(sb, composition.PreInterceptors);
            AppendFrozenSegment(sb, composition.IndirectPreInterceptors);
            AppendFrozenSegment(sb, composition.PostInterceptors);
            AppendFrozenSegment(sb, composition.IndirectPostInterceptors);
            AppendFrozenSegment(sb, composition.ExceptionInterceptors);
            AppendFrozenSegment(sb, composition.IndirectExceptionInterceptors);
            AppendFrozenSegment(sb, composition.FinalInterceptors);
            AppendFrozenSegment(sb, composition.IndirectFinalInterceptors, last: true);
            sb.AppendLine("            ));");
        }

        sb.AppendLine("        }");
    }

    private const string FrozenCompositionFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchRoots.FrozenComposition";
    private const string FrozenParticipantFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchRoots.FrozenParticipant";

    private static void AppendFrozenSegment(
        StringBuilder sb, System.Collections.Immutable.ImmutableArray<FrozenParticipantModel> segment, bool last = false)
    {
        if (segment.IsEmpty)
        {
            sb.Append("                global::System.Array.Empty<").Append(FrozenParticipantFullName).Append(">()");
        }
        else
        {
            sb.Append("                new ").Append(FrozenParticipantFullName).Append("[] { ");

            for (var i = 0; i < segment.Length; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }

                sb.Append("new ").Append(FrozenParticipantFullName)
                  .Append("(typeof(").Append(segment[i].TypeofExpression).Append(')');

                if (segment[i].GroupsExpression is { } groupsExpression)
                {
                    sb.Append(", ").Append(groupsExpression);
                }

                sb.Append(')');
            }

            sb.Append(" }");
        }

        sb.AppendLine(last ? string.Empty : ",");
    }

    private const string HandlersNamespace = "global::Stella.Ergosfare.Core.Abstractions.Handlers.";
    private const string StagedCompositionFullName = "global::Stella.Ergosfare.Core.Abstractions.StagedPlans.StagedPlanKey";
    private const string ExecutionContextFullName = "global::Stella.Ergosfare.Core.Abstractions.ErgosfareContext";
    private const string AbortedExceptionFullName = "global::Stella.Ergosfare.Core.Abstractions.Exceptions.ExecutionAbortedException";
    private const string ValueTaskFullName = "global::System.Threading.Tasks.ValueTask";

    /// <summary>
    ///     The result representation of a pipeline that produces none. Distinct from
    ///     <see cref="ValueTaskFullName"/>, which stays the completion signal: a void plan
    ///     still returns a <c>ValueTask</c>, it just carries <c>Unit.Value</c> in its slot.
    /// </summary>
    private const string UnitFullName = "global::Stella.Ergosfare.Core.Abstractions.Unit";
    private const string GetRequiredServiceFullName = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";

    /// <summary>
    ///     Emits one sealed plan class per staged plan: the baked composition plus a
    ///     bespoke <c>Execute</c> reproducing the runtime strategy's semantics exactly for
    ///     the baked pipeline — pre stages in order (each may rewrite the message), the
    ///     handler, post stages with result rewrite, exception stages (skipped for
    ///     <c>ExecutionAbortedException</c>, swallowing the exception once they ran, like
    ///     the strategy), and final stages that always run. Casts mirror the strategy and
    ///     invoker code shapes, including the erased-generic unbox semantics for
    ///     value-typed results. Participants resolve from the dispatching provider — what
    ///     the runtime references do outside memoized mode, which the hosting executor's
    ///     gate excludes.
    /// </summary>
    private static void EmitStagedPlanClasses(
        StringBuilder sb,
        ref bool wroteMember,
        IReadOnlyList<StagedPlanModel> stagedPlans,
        bool supportsDirectConstruction)
    {
        for (var i = 0; i < stagedPlans.Count; i++)
        {
            var plan = stagedPlans[i];
            var isVoid = plan.ResultTypeExpression is null;
            var emitDirect = supportsDirectConstruction && plan.SupportsDirectConstruction;

            StartMember(sb, ref wroteMember);
            sb.Append("        private sealed class StagedPlan").Append(i).Append(" : global::Stella.Ergosfare.Core.Abstractions.StagedPlans.");

            if (plan.IsBroadcast)
            {
                sb.Append("StagedBroadcastPlan<").Append(plan.MessageTypeExpression).AppendLine(">");
            }
            else if (isVoid)
            {
                sb.Append("StagedVoidPlan<").Append(plan.MessageTypeExpression).AppendLine(">");
            }
            else
            {
                sb.Append("StagedResultPlan<").Append(plan.MessageTypeExpression)
                  .Append(", ").Append(plan.ResultTypeExpression).AppendLine(">");
            }

            sb.AppendLine("        {");

            sb.Append("            private static readonly ").Append(StagedCompositionFullName)
              .Append(" BakedComposition = new ").Append(StagedCompositionFullName).AppendLine("(");
            AppendHandlerSegment(sb, plan.Handlers);
            sb.AppendLine(",");
            AppendHandlerSegment(sb, plan.IndirectHandlers);
            sb.AppendLine(",");
            AppendCompositionStage(sb, plan.PreCalls);
            sb.AppendLine(",");
            AppendCompositionStage(sb, plan.PostCalls);
            sb.AppendLine(",");
            AppendCompositionStage(sb, plan.ExceptionCalls);
            sb.AppendLine(",");
            AppendCompositionStage(sb, plan.FinalCalls);

            if (plan.AdapterKind != StagedResultAdapterKind.None)
            {
                // The baked adapter identity: the hosting executor only trusts the plan
                // while the runtime-bound adapter of the slot is exactly this type.
                sb.AppendLine(",");
                sb.Append("                typeof(").Append(plan.ResultAdapterTypeExpression).Append(')');
            }

            sb.AppendLine(");");
            sb.AppendLine();

            if (plan.AdapterKind == StagedResultAdapterKind.Custom)
            {
                sb.Append("            private static readonly ").Append(plan.ResultAdapterTypeExpression)
                  .Append(" ResultAdapter = new ").Append(plan.ResultAdapterTypeExpression).AppendLine("();");
                sb.AppendLine();
            }
            sb.Append("            public override ").Append(StagedCompositionFullName).AppendLine(" Composition");
            sb.AppendLine("            {");
            sb.AppendLine("                get { return BakedComposition; }");
            sb.AppendLine("            }");
            sb.AppendLine();

            sb.Append("            public override async ").Append(ValueTaskFullName);

            if (!isVoid)
            {
                sb.Append('<').Append(plan.ResultTypeExpression).Append('>');
            }

            sb.AppendLine(" Execute(");
            sb.Append("                ").Append(plan.MessageTypeExpression).AppendLine(" message,");
            sb.Append("                ").Append(ExecutionContextFullName).AppendLine(" context,");
            sb.AppendLine("                global::System.IServiceProvider serviceProvider)");
            sb.AppendLine("            {");

            if (isVoid)
            {
                EmitVoidExecuteBody(sb, plan, direct: false);
            }
            else
            {
                EmitResultExecuteBody(sb, plan, direct: false);
            }

            sb.AppendLine("            }");

            // The direct-construction variant: the same pipeline with every participant
            // constructed via `new` — used by the hosting executor only after it verified
            // every participant's plain transient registration.
            if (emitDirect)
            {
                sb.AppendLine();
                sb.AppendLine("            public override bool SupportsDirectConstruction");
                sb.AppendLine("            {");
                sb.AppendLine("                get { return true; }");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.Append("            public override async ").Append(ValueTaskFullName);

                if (!isVoid)
                {
                    sb.Append('<').Append(plan.ResultTypeExpression).Append('>');
                }

                sb.AppendLine(" ExecuteDirect(");
                sb.Append("                ").Append(plan.MessageTypeExpression).AppendLine(" message,");
                sb.Append("                ").Append(ExecutionContextFullName).AppendLine(" context,");
                sb.AppendLine("                global::System.IServiceProvider serviceProvider)");
                sb.AppendLine("            {");

                if (isVoid)
                {
                    EmitVoidExecuteBody(sb, plan, direct: true);
                }
                else
                {
                    EmitResultExecuteBody(sb, plan, direct: true);
                }

                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
        }
    }

    /// <summary>
    ///     Appends one baked handler segment. A single-handler plan writes a one-element
    ///     array and an empty second segment, which is the same comparison the runtime gate
    ///     applies to a broadcast — one shape, one gate.
    /// </summary>
    private static void AppendHandlerSegment(
        StringBuilder sb, System.Collections.Immutable.ImmutableArray<StagedHandlerModel> handlers)
    {
        if (handlers.IsEmpty)
        {
            sb.Append("                global::System.Array.Empty<global::System.Type>()");
            return;
        }

        sb.Append("                new global::System.Type[] { ");

        for (var i = 0; i < handlers.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("typeof(").Append(handlers[i].TypeExpression).Append(')');
        }

        sb.Append(" }");
    }

    private static void AppendCompositionStage(StringBuilder sb, System.Collections.Immutable.ImmutableArray<StagedCallModel> calls)
    {
        if (calls.IsEmpty)
        {
            sb.Append("                global::System.Array.Empty<global::System.Type>()");
            return;
        }

        sb.Append("                new global::System.Type[] { ");

        for (var i = 0; i < calls.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("typeof(").Append(calls[i].TypeExpression).Append(')');
        }

        sb.Append(" }");
    }

    private static void AppendResolve(StringBuilder sb, string typeExpression)
        => sb.Append(GetRequiredServiceFullName).Append('<').Append(typeExpression).Append(">(serviceProvider)");

    /// <summary>
    ///     A participant expression: the container resolution, or — in the
    ///     direct-construction variant — the participant's <c>new</c> expression.
    /// </summary>
    private static void AppendParticipant(StringBuilder sb, string typeExpression, string? constructionExpression)
    {
        if (constructionExpression is null)
        {
            AppendResolve(sb, typeExpression);
        }
        else
        {
            sb.Append(constructionExpression);
        }
    }

    /// <summary>
    ///     The strategy/invoker-parity cast of the chained object result back to the
    ///     pipeline result type.
    /// </summary>
    /// <param name="targetAcceptsNull">
    ///     Whether the stage being called declares its result parameter as
    ///     <c>TResult?</c>. Exception and final interceptors do; post interceptors declare
    ///     a plain <c>TResult</c>. The distinction is load-bearing for reference-typed
    ///     results: a cast to <c>TResult?</c> resets the expression's nullable state to
    ///     maybe-null however non-null the chain variable is, so handing one to a post
    ///     interceptor is CS8604 in the consumer's build — and a build failure outright
    ///     where warnings are errors.
    /// </param>
    private static string ResultCast(string resultExpression, bool resultIsValueType, bool targetAcceptsNull, string operand)
        => resultIsValueType
            ? "(" + resultExpression + ")" + operand + "!"
            : targetAcceptsNull
                ? "(" + resultExpression + "?)" + operand
                : "(" + resultExpression + ")" + operand;

    /// <summary>
    ///     Emits the plugin observers declared at one plan boundary: a plain call for a
    ///     <c>void</c> method — which never enters the state machine — and an awaited one for
    ///     a <c>ValueTask</c> method. The method's generics are closed over the plan's own
    ///     message and result types, so a value-typed message or result crosses the call
    ///     unboxed, and its dependencies bind positionally to what the boundary has.
    /// </summary>
    /// <param name="resultExpression">
    ///     The local holding the pipeline result at this boundary, or <c>null</c> where the
    ///     body has none. A resultless pipeline's observers declare no result parameter, so
    ///     the two go together; before the handler has run, the local is the plan's
    ///     <c>default</c> and the observer reads it as such.
    /// </param>
    private static void EmitPluginCalls(
        StringBuilder sb, StagedPlanModel plan, PluginStage stage, string? resultExpression, string indent)
    {
        foreach (var call in plan.PluginCalls)
        {
            if (call.Stage != stage)
            {
                continue;
            }

            sb.Append(indent);

            if (call.IsAsync)
            {
                sb.Append("await ");
            }

            if (call.IsStatic)
            {
                sb.Append(call.ServiceTypeExpression);
            }
            else
            {
                // Resolution parity: the plugin service comes from the dispatching provider
                // like every other participant, so a container's own registration overrides
                // still decide what runs.
                AppendResolve(sb, call.ServiceTypeExpression);
            }

            sb.Append('.').Append(call.MethodName)
              .Append('<').Append(plan.MessageTypeExpression);

            if (plan.ResultTypeExpression is not null)
            {
                sb.Append(", ").Append(plan.ResultTypeExpression);
            }

            sb.Append(">(");

            for (var i = 0; i < call.Parameters.Length; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }

                switch (call.Parameters[i].Kind)
                {
                    case PluginParameterKind.Message:
                        sb.Append("message");
                        break;
                    case PluginParameterKind.Result:
                        sb.Append(resultExpression ?? "default!");
                        break;
                    case PluginParameterKind.Context:
                        sb.Append("context");
                        break;
                    default:
                        AppendResolve(sb, call.Parameters[i].TypeExpression!);
                        break;
                }
            }

            sb.AppendLine(");");
        }
    }

    /// <summary>
    ///     Emits the plan's main-handler calls: the directly registered segment, then the
    ///     covariantly matched one. A single-handler pipeline is the same code with one
    ///     entry and an empty second segment.
    /// </summary>
    /// <remarks>
    ///     The pre- and post-handler plugin boundaries are emitted <b>per handler</b>: they
    ///     name the seam around a handler, and a broadcast has one such seam per delivery.
    ///     At N = 1 that is exactly where they were before, so a command or query plan is
    ///     byte-identical to what it emitted when the boundary was written by the body.
    /// </remarks>
    private static void EmitHandlerCalls(StringBuilder sb, StagedPlanModel plan, bool direct, string indent)
    {
        EmitHandlerSegment(sb, plan, plan.Handlers, direct, indent);
        EmitHandlerSegment(sb, plan, plan.IndirectHandlers, direct, indent);
    }

    private static void EmitHandlerSegment(
        StringBuilder sb,
        StagedPlanModel plan,
        System.Collections.Immutable.ImmutableArray<StagedHandlerModel> handlers,
        bool direct,
        string indent)
    {
        foreach (var handler in handlers)
        {
            EmitPluginCalls(sb, plan, PluginStage.PreMainHandler, null, indent);
            sb.Append(indent).Append("await ");
            AppendParticipant(sb, handler.TypeExpression, direct ? handler.ConstructionExpression : null);
            sb.AppendLine(".HandleAsync(message, context);");
            EmitPluginCalls(sb, plan, PluginStage.PostMainHandler, null, indent);
        }
    }

    private static void EmitPreCalls(StringBuilder sb, StagedPlanModel plan, bool direct, string indent)
    {
        foreach (var call in plan.PreCalls)
        {
            sb.Append(indent).Append("message = (").Append(plan.MessageTypeExpression).Append(") ");

            if (call.Arm == StagedCallArm.Sync)
            {
                sb.Append("((").Append(HandlersNamespace).Append("IPreInterceptor<").Append(plan.MessageTypeExpression).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.AppendLine(").Handle(message, context);");
            }
            else
            {
                sb.Append("await ((").Append(HandlersNamespace).Append("IAsyncPreInterceptor<").Append(plan.MessageTypeExpression).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.AppendLine(").HandleAsync(message, context);");
            }
        }
    }

    /// <summary>
    ///     Emits one interceptor-chain call for a result-carrying stage, rewriting the
    ///     given object-typed chain variable exactly as the runtime invoker loop does.
    /// </summary>
    private static void EmitChainCall(
        StringBuilder sb,
        StagedPlanModel plan,
        StagedCallModel call,
        bool direct,
        string stageInterface,
        string chainVariable,
        string? exceptionArgument,
        string indent)
    {
        var pipelineResult = plan.ResultTypeExpression ?? UnitFullName;
        var pipelineResultIsValueType = plan.ResultTypeExpression is not null && plan.ResultIsValueType;
        var extraArgument = exceptionArgument is null ? string.Empty : ", " + exceptionArgument;

        // The exception argument doubles as the stage discriminator: only the exception
        // stage carries one, and only the exception stage declares its result parameter
        // nullable. The post stage takes TResult and object, not TResult? and object?.
        var targetAcceptsNull = exceptionArgument is not null;

        sb.Append(indent).Append(chainVariable).Append(" = ");

        switch (call.Arm)
        {
            case StagedCallArm.AsyncTyped:
                sb.Append("await ((").Append(HandlersNamespace).Append("IAsync").Append(stageInterface)
                  .Append('<').Append(plan.MessageTypeExpression).Append(", ").Append(pipelineResult).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.Append(").HandleAsync(message, ")
                  .Append(ResultCast(pipelineResult, pipelineResultIsValueType, targetAcceptsNull, chainVariable))
                  .Append(extraArgument).AppendLine(", context);");
                break;
            case StagedCallArm.AsyncAgnostic:
                sb.Append("await ((").Append(HandlersNamespace).Append("IAsync").Append(stageInterface)
                  .Append('<').Append(plan.MessageTypeExpression).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.Append(").HandleAsync(message, ").Append(chainVariable)
                  .Append(exceptionArgument is null ? "!" : string.Empty)
                  .Append(extraArgument).AppendLine(", context);");
                break;
            default:
                sb.Append("((").Append(HandlersNamespace).Append('I').Append(stageInterface)
                  .Append('<').Append(plan.MessageTypeExpression).Append(", ").Append(pipelineResult).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.Append(").Handle(message, ")
                  .Append(ResultCast(pipelineResult, pipelineResultIsValueType, targetAcceptsNull, chainVariable))
                  .Append(extraArgument).AppendLine(", context);");
                break;
        }
    }

    private static void EmitFinalCalls(StringBuilder sb, StagedPlanModel plan, bool direct, string resultExpressionText, string indent)
    {
        var pipelineResult = plan.ResultTypeExpression ?? UnitFullName;
        var pipelineResultIsValueType = plan.ResultTypeExpression is not null && plan.ResultIsValueType;

        // Final interceptors declare `TResult? result` — the stage runs from a finally,
        // so the pipeline may never have produced one.
        const bool targetAcceptsNull = true;

        foreach (var call in plan.FinalCalls)
        {
            switch (call.Arm)
            {
                case StagedCallArm.AsyncTyped:
                    sb.Append(indent).Append("await ((").Append(HandlersNamespace).Append("IAsyncFinalInterceptor<")
                      .Append(plan.MessageTypeExpression).Append(", ").Append(pipelineResult).Append(">)");
                    AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                    sb.Append(").HandleAsync(message, ")
                      .Append(ResultCast(pipelineResult, pipelineResultIsValueType, targetAcceptsNull, resultExpressionText))
                      .AppendLine(", exception, context);");
                    break;
                case StagedCallArm.AsyncAgnostic:
                    sb.Append(indent).Append("await ((").Append(HandlersNamespace).Append("IAsyncFinalInterceptor<")
                      .Append(plan.MessageTypeExpression).Append(">)");
                    AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                    sb.Append(").HandleAsync(message, ").Append(resultExpressionText).AppendLine(", exception, context);");
                    break;
                default:
                    sb.Append(indent).Append("((").Append(HandlersNamespace).Append("IFinalInterceptor<")
                      .Append(plan.MessageTypeExpression).Append(", ").Append(pipelineResult).Append(">)");
                    AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                    sb.Append(").Handle(message, ")
                      .Append(ResultCast(pipelineResult, pipelineResultIsValueType, targetAcceptsNull, resultExpressionText))
                      .AppendLine(", exception, context);");
                    break;
            }
        }

        // The plugin's final observers close the stage: nothing they do can keep an
        // interceptor from running, and they see whatever result the stage settled on.
        EmitPluginCalls(sb, plan, PluginStage.OnFinal,
            plan.ResultTypeExpression is null ? null : resultExpressionText, indent);
    }

    /// <summary>Whether the plan's exception stage carries an unfiltered participant — one that accepts every exception.</summary>
    private static bool StageAlwaysMatches(StagedPlanModel plan)
    {
        foreach (var call in plan.ExceptionCalls)
        {
            if (call.ExceptionFilterExpression is null)
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    ///     Emits the exception stage's chain calls, guarding every filtered participant
    ///     with the compile-time <c>is</c> test its runtime filter probe would apply.
    ///     Tracks the match flag only when the caller has an unmatched outcome to emit
    ///     and no unfiltered participant makes a miss impossible.
    /// </summary>
    /// <returns>Whether an unfiltered participant guarantees the stage always matches.</returns>
    private static bool EmitExceptionCallLoop(
        StringBuilder sb, StagedPlanModel plan, bool direct, string chainVariable, string exceptionVariable,
        bool trackMatched, string indent)
    {
        var alwaysMatches = StageAlwaysMatches(plan);
        var emitFlag = trackMatched && !alwaysMatches;

        if (emitFlag)
        {
            sb.Append(indent).AppendLine("var matchedExceptionInterceptor = false;");
        }

        foreach (var call in plan.ExceptionCalls)
        {
            if (call.ExceptionFilterExpression is null)
            {
                EmitChainCall(sb, plan, call, direct, "ExceptionInterceptor", chainVariable, exceptionVariable, indent);
                continue;
            }

            sb.Append(indent).Append("if (").Append(exceptionVariable).Append(" is ")
              .Append(call.ExceptionFilterExpression).AppendLine(")");
            sb.Append(indent).AppendLine("{");

            if (emitFlag)
            {
                sb.Append(indent).AppendLine("    matchedExceptionInterceptor = true;");
            }

            EmitChainCall(sb, plan, call, direct, "ExceptionInterceptor", chainVariable, exceptionVariable, indent + "    ");
            sb.Append(indent).AppendLine("}");
        }

        return alwaysMatches;
    }

    /// <summary>
    ///     The catch-context exception stage: chain calls plus the runtime stage's exact
    ///     unmatched outcome — a bare rethrow.
    /// </summary>
    /// <remarks>
    ///     When every participant is filtered, none of them may turn out to accept the
    ///     exception — and a stage that ran nobody has handled nothing, so the plan
    ///     rethrows exactly as the runtime stage does. A single unfiltered participant
    ///     makes that impossible, and the flag is not emitted at all.
    /// </remarks>
    private static void EmitExceptionCalls(
        StringBuilder sb, StagedPlanModel plan, bool direct, string chainVariable, string indent)
    {
        if (EmitExceptionCallLoop(sb, plan, direct, chainVariable, "e", trackMatched: true, indent))
        {
            return;
        }

        sb.Append(indent).AppendLine("if (!matchedExceptionInterceptor)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    throw;");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitVoidExecuteBody(StringBuilder sb, StagedPlanModel plan, bool direct)
    {
        var needsResult = !plan.PostCalls.IsEmpty || !plan.ExceptionCalls.IsEmpty || !plan.FinalCalls.IsEmpty;
        var needsGuards = needsResult || plan.PluginNeedsGuards;

        if (!needsGuards)
        {
            // Pre-only pipeline: with zero exception and final stages there is nothing to
            // skip and nothing to clean up, so no guard at all — exceptions and aborts
            // alike travel out untouched. A plugin observing only the four unguarded
            // boundaries keeps the body exactly this shape.
            EmitPluginCalls(sb, plan, PluginStage.PipelineStart, null, "                ");
            EmitPreCalls(sb, plan, direct, "                ");
            EmitHandlerCalls(sb, plan, direct, "                ");
            EmitPluginCalls(sb, plan, PluginStage.AfterPost, null, "                ");
            return;
        }

        sb.AppendLine("                object? result = null;");
        sb.AppendLine("                global::System.Exception? exception = null;");
        sb.AppendLine("                var aborted = false;");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        EmitPluginCalls(sb, plan, PluginStage.PipelineStart, null, "                    ");
        EmitPreCalls(sb, plan, direct, "                    ");
        EmitHandlerCalls(sb, plan, direct, "                    ");
        sb.Append("                    result = ").Append(UnitFullName).AppendLine(".Value;");

        if (!plan.PostCalls.IsEmpty)
        {
            foreach (var call in plan.PostCalls)
            {
                EmitChainCall(sb, plan, call, direct, "PostInterceptor", "result", null, "                    ");
            }

            // The strategy's post epilogue: a null post result restores the pipeline's
            // one result value; anything that is not a Unit fails the closed nullable
            // cast, exactly like the strategy's own cast would.
            sb.Append("                    var invokedPostResult = (").Append(UnitFullName).AppendLine("?) result;");
            sb.Append("                    result = invokedPostResult == null ? ").Append(UnitFullName).AppendLine(".Value : result;");
        }

        EmitPluginCalls(sb, plan, PluginStage.AfterPost, null, "                    ");
        sb.AppendLine("                }");
        // A participant stopped the pipeline: nothing else runs — not the exception stage,
        // not the final stage — and the signal continues to the caller. The strategy's own
        // abort arm, emitted.
        sb.Append("                catch (").Append(AbortedExceptionFullName).AppendLine(")");
        sb.AppendLine("                {");
        sb.AppendLine("                    aborted = true;");
        sb.AppendLine("                    throw;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (global::System.Exception e)");
        sb.AppendLine("                {");
        sb.AppendLine("                    exception = e;");
        // Before the interceptor stage, deliberately: an exception interceptor that returns
        // a value swallows the exception, and an observer whose job is to see every failure
        // must not depend on whether one did.
        EmitPluginCalls(sb, plan, PluginStage.OnException, null, "                    ");

        if (plan.ExceptionCalls.IsEmpty)
        {
            sb.AppendLine("                    throw;");
        }
        else
        {
            sb.AppendLine("                    var resultBeforeExceptions = result;");

            EmitExceptionCalls(sb, plan, direct, "result", "                    ");

            sb.Append("                    var invokedExceptionResult = (").Append(UnitFullName).AppendLine("?) result;");
            sb.AppendLine("                    result = invokedExceptionResult == null ? resultBeforeExceptions : result;");
        }

        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (!aborted)");
        sb.AppendLine("                    {");
        EmitFinalCalls(sb, plan, direct, "result", "                        ");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
    }

    private static void EmitResultExecuteBody(StringBuilder sb, StagedPlanModel plan, bool direct)
    {
        if (plan.AdapterKind != StagedResultAdapterKind.None)
        {
            EmitAdaptedResultExecuteBody(sb, plan, direct);
            return;
        }

        var resultExpression = plan.ResultTypeExpression!;
        var needsGuards = !plan.PostCalls.IsEmpty || !plan.ExceptionCalls.IsEmpty || !plan.FinalCalls.IsEmpty
                          || plan.PluginNeedsGuards;

        if (!needsGuards)
        {
            // Pre-only pipeline; see the void body. No guard: with nothing to skip and
            // nothing to clean up, exceptions and aborts alike travel out untouched.
            EmitPluginCalls(sb, plan, PluginStage.PipelineStart, null, "                ");
            EmitPreCalls(sb, plan, direct, "                ");
            EmitPluginCalls(sb, plan, PluginStage.PreMainHandler, null, "                ");

            if (!plan.PluginCalls.IsEmpty)
            {
                // The handler's result has observers after it, so it lands in a local
                // instead of going straight out.
                sb.Append("                ").Append(resultExpression).Append(" result = await ");
                AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
                sb.AppendLine(".HandleAsync(message, context);");
                EmitPluginCalls(sb, plan, PluginStage.PostMainHandler, "result", "                ");
                EmitPluginCalls(sb, plan, PluginStage.AfterPost, "result", "                ");
                sb.AppendLine("                return result;");
                return;
            }

            sb.Append("                return await ");
            AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
            sb.AppendLine(".HandleAsync(message, context);");
            return;
        }

        sb.Append("                ").Append(resultExpression).AppendLine(" result = default!;");
        sb.AppendLine("                global::System.Exception? exception = null;");
        sb.AppendLine("                var aborted = false;");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        EmitPluginCalls(sb, plan, PluginStage.PipelineStart, null, "                    ");
        EmitPreCalls(sb, plan, direct, "                    ");
        EmitPluginCalls(sb, plan, PluginStage.PreMainHandler, null, "                    ");
        sb.Append("                    result = await ");
        AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
        sb.AppendLine(".HandleAsync(message, context);");
        EmitPluginCalls(sb, plan, PluginStage.PostMainHandler, "result", "                    ");

        if (!plan.PostCalls.IsEmpty)
        {
            sb.AppendLine("                    object? postChain = result;");

            foreach (var call in plan.PostCalls)
            {
                EmitChainCall(sb, plan, call, direct, "PostInterceptor", "postChain", null, "                    ");
            }

            if (plan.ResultIsValueType)
            {
                // The strategy's erased (TResult?) cast is a plain unbox for value-typed
                // results — a null post result throws there, so no null branch exists.
                sb.Append("                    result = (").Append(resultExpression).AppendLine(") postChain!;");
            }
            else
            {
                sb.Append("                    var postResult = (").Append(resultExpression).AppendLine("?) postChain;");
                sb.AppendLine("                    result = postResult == null ? result : postResult;");
            }
        }

        EmitPluginCalls(sb, plan, PluginStage.AfterPost, "result", "                    ");
        sb.AppendLine("                }");
        // A participant stopped the pipeline: nothing else runs — not the exception stage,
        // not the final stage — and the signal continues to the caller.
        sb.Append("                catch (").Append(AbortedExceptionFullName).AppendLine(")");
        sb.AppendLine("                {");
        sb.AppendLine("                    aborted = true;");
        sb.AppendLine("                    throw;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (global::System.Exception e)");
        sb.AppendLine("                {");
        sb.AppendLine("                    exception = e;");
        // See the void body: the observers run ahead of the interceptor stage so a swallowed
        // exception is still an observed one.
        EmitPluginCalls(sb, plan, PluginStage.OnException, "result", "                    ");

        if (plan.ExceptionCalls.IsEmpty)
        {
            sb.AppendLine("                    throw;");
        }
        else
        {
            sb.AppendLine("                    object? exceptionChain = result;");

            EmitExceptionCalls(sb, plan, direct, "exceptionChain", "                    ");

            if (plan.ResultIsValueType)
            {
                sb.Append("                    result = (").Append(resultExpression).AppendLine(") exceptionChain!;");
            }
            else
            {
                sb.Append("                    var exceptionResult = (").Append(resultExpression).AppendLine("?) exceptionChain;");
                sb.AppendLine("                    result = exceptionResult == null ? result : exceptionResult;");
            }
        }

        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        sb.AppendLine("                    if (!aborted)");
        sb.AppendLine("                    {");
        EmitFinalCalls(sb, plan, direct, "result", "                        ");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                return result;");
    }

    private const string ExceptionDispatchInfoFullName = "global::System.Runtime.ExceptionServices.ExceptionDispatchInfo";

    /// <summary>
    ///     The materialization of a real throw into a failed carrier: the carrier's own
    ///     <c>Fail</c> for the native kind, the baked adapter's <c>Materialize</c> otherwise.
    /// </summary>
    private static string MaterializeExpression(StagedPlanModel plan, string exceptionVariable)
        => plan.AdapterKind == StagedResultAdapterKind.Native
            ? plan.ResultTypeExpression + ".Fail(" + exceptionVariable + ")"
            : "ResultAdapter.Materialize(" + exceptionVariable + ")";

    /// <summary>
    ///     The value-channel probe of the handler's result: a direct field read for the
    ///     native carrier, the baked adapter's <c>TryGetException</c> otherwise. Only the
    ///     failure lands in <c>exception</c> — <c>result</c> already is the carrier.
    /// </summary>
    private static void EmitHandlerProbe(StringBuilder sb, StagedPlanModel plan, string indent)
    {
        if (plan.AdapterKind == StagedResultAdapterKind.Native)
        {
            sb.Append(indent).AppendLine("if (result.Exception is { } carriedException)");
        }
        else
        {
            sb.Append(indent).AppendLine(
                "if (ResultAdapter.TryGetException(in result, out var carriedException) && carriedException is not null)");
        }

        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    exception = carriedException;");
        sb.Append(indent).AppendLine("}");
    }

    /// <summary>
    ///     The value-channel probe of one post-interceptor's chained result: the failed
    ///     carrier the interceptor produced becomes the pipeline result, its failure the
    ///     stage transition — mirroring the runtime post-invocation loop's probe.
    /// </summary>
    private static void EmitPostProbe(StringBuilder sb, StagedPlanModel plan, int probeIndex, string indent)
    {
        var carrier = "postCarrier" + probeIndex;
        var failure = "postException" + probeIndex;

        sb.Append(indent).Append("if (postChain is ").Append(plan.ResultTypeExpression).Append(' ').Append(carrier);

        if (plan.AdapterKind == StagedResultAdapterKind.Native)
        {
            sb.Append(" && ").Append(carrier).Append(".Exception is { } ").Append(failure).AppendLine(")");
        }
        else
        {
            sb.Append(" && ResultAdapter.TryGetException(in ").Append(carrier).Append(", out var ").Append(failure)
              .Append(") && ").Append(failure).AppendLine(" is not null)");
        }

        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    result = ").Append(carrier).AppendLine(";");
        sb.Append(indent).Append("    exception = ").Append(failure).AppendLine(";");
        sb.Append(indent).AppendLine("}");
    }

    /// <summary>
    ///     The strategy-parity merge of an object-typed chain back into <c>result</c>; see
    ///     the unadapted bodies for the value-type unbox reasoning.
    /// </summary>
    private static void EmitChainMerge(
        StringBuilder sb, StagedPlanModel plan, string chainVariable, string mergedVariable, string indent)
    {
        var resultExpression = plan.ResultTypeExpression!;

        if (plan.ResultIsValueType)
        {
            sb.Append(indent).Append("result = (").Append(resultExpression).Append(") ").Append(chainVariable).AppendLine("!;");
        }
        else
        {
            sb.Append(indent).Append("var ").Append(mergedVariable).Append(" = (").Append(resultExpression)
              .Append("?) ").Append(chainVariable).AppendLine(";");
            sb.Append(indent).Append("result = ").Append(mergedVariable).Append(" == null ? result : ")
              .Append(mergedVariable).AppendLine(";");
        }
    }

    /// <summary>
    ///     The adapted twin of <see cref="EmitResultExecuteBody"/>: the result slot has a
    ///     baked adapter, so the body carries the value channel — a probe after the handler
    ///     and after every post-interceptor enters the exception stage as a plain branch,
    ///     with no throw paid anywhere. The stage itself runs between the pipeline
    ///     try/catch and the final stage. A real throw is caught and — when the carrier
    ///     can absorb one — materialized into a failed carrier; only a non-materializable
    ///     carrier keeps the classic unhandled outcome, rethrown via
    ///     <see cref="ExceptionDispatchInfoFullName"/> after the final stage.
    /// </summary>
    private static void EmitAdaptedResultExecuteBody(StringBuilder sb, StagedPlanModel plan, bool direct)
    {
        var resultExpression = plan.ResultTypeExpression!;
        var materializes = plan.ResultAdapterMaterializes;
        var needsGuards = !plan.PostCalls.IsEmpty || !plan.ExceptionCalls.IsEmpty || !plan.FinalCalls.IsEmpty
                          || !plan.PluginCalls.IsEmpty;

        if (!needsGuards)
        {
            // Pre-only pipeline: there is no stage to tell, so a carried failure either
            // flows out inside its (materializable) carrier or keeps the classic contract
            // and surfaces as a throw; a real throw materializes when the carrier can
            // absorb one and propagates unchanged otherwise.
            sb.AppendLine("                try");
            sb.AppendLine("                {");
            EmitPreCalls(sb, plan, direct, "                    ");

            if (materializes)
            {
                sb.Append("                    return await ");
                AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
                sb.AppendLine(".HandleAsync(message, context);");
            }
            else
            {
                sb.Append("                    var handlerResult = await ");
                AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
                sb.AppendLine(".HandleAsync(message, context);");
                sb.AppendLine();
                sb.AppendLine("                    if (ResultAdapter.TryGetException(in handlerResult, out var carriedException) && carriedException is not null)");
                sb.AppendLine("                    {");
                sb.AppendLine("                        throw carriedException;");
                sb.AppendLine("                    }");
                sb.AppendLine();
                sb.AppendLine("                    return handlerResult;");
            }

            sb.AppendLine("                }");
            sb.Append("                catch (").Append(AbortedExceptionFullName).AppendLine(")");
            sb.AppendLine("                {");
            sb.AppendLine("                    return default!;");
            sb.AppendLine("                }");

            if (materializes)
            {
                sb.AppendLine("                catch (global::System.Exception e)");
                sb.AppendLine("                {");
                sb.Append("                    return ").Append(MaterializeExpression(plan, "e")).AppendLine(";");
                sb.AppendLine("                }");
            }

            return;
        }

        // An unhandled failure needs a post-final rethrow slot only when the carrier
        // cannot absorb one and the stage cannot be proven to always match.
        var needsUnhandled = !materializes && !StageAlwaysMatches(plan);

        sb.Append("                ").Append(resultExpression).AppendLine(" result = default!;");
        sb.AppendLine("                global::System.Exception? exception = null;");

        if (needsUnhandled)
        {
            sb.Append("                ").Append(ExceptionDispatchInfoFullName).AppendLine("? unhandledException = null;");
        }

        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine("                    try");
        sb.AppendLine("                    {");
        EmitPluginCalls(sb, plan, PluginStage.PipelineStart, null, "                        ");
        EmitPreCalls(sb, plan, direct, "                        ");
        EmitPluginCalls(sb, plan, PluginStage.PreMainHandler, null, "                        ");
        sb.Append("                        result = await ");
        AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
        sb.AppendLine(".HandleAsync(message, context);");
        sb.AppendLine();
        EmitHandlerProbe(sb, plan, "                        ");
        EmitPluginCalls(sb, plan, PluginStage.PostMainHandler, "result", "                        ");

        if (!plan.PostCalls.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine("                        object? postChain = result;");

            var probeIndex = 0;

            foreach (var call in plan.PostCalls)
            {
                sb.AppendLine();
                sb.AppendLine("                        if (exception is null)");
                sb.AppendLine("                        {");
                EmitChainCall(sb, plan, call, direct, "PostInterceptor", "postChain", null, "                            ");
                EmitPostProbe(sb, plan, probeIndex++, "                            ");
                sb.AppendLine("                        }");
            }

            sb.AppendLine();
            sb.AppendLine("                        if (exception is null)");
            sb.AppendLine("                        {");
            EmitChainMerge(sb, plan, "postChain", "postResult", "                            ");
            sb.AppendLine("                        }");
        }

        if (plan.HasPluginCalls(PluginStage.AfterPost))
        {
            // The value channel may already carry a failure here; the observers see the
            // result the stage settled on either way, which is what the boundary means.
            sb.AppendLine();
            EmitPluginCalls(sb, plan, PluginStage.AfterPost, "result", "                        ");
        }

        sb.AppendLine("                    }");
        // A short circuit, not a failure; see the unadapted body.
        sb.Append("                    catch (").Append(AbortedExceptionFullName).AppendLine(")");
        sb.AppendLine("                    {");
        sb.AppendLine("                    }");
        sb.AppendLine("                    catch (global::System.Exception e)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        exception = e;");

        if (materializes)
        {
            sb.Append("                        result = ").Append(MaterializeExpression(plan, "e")).AppendLine(";");
        }

        sb.AppendLine("                    }");

        if (plan.HasPluginCalls(PluginStage.OnException))
        {
            // Its own branch, ahead of the interceptor stage: the adapted body reaches this
            // point on a carried failure too, and the observer is told either way.
            sb.AppendLine();
            sb.AppendLine("                    if (exception is not null)");
            sb.AppendLine("                    {");
            EmitPluginCalls(sb, plan, PluginStage.OnException, "result", "                        ");
            sb.AppendLine("                    }");
        }

        if (!plan.ExceptionCalls.IsEmpty)
        {
            sb.AppendLine();
            sb.AppendLine("                    if (exception is not null)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        object? exceptionChain = result;");
            EmitExceptionCallLoop(sb, plan, direct, "exceptionChain", "exception",
                trackMatched: needsUnhandled, "                        ");

            if (needsUnhandled)
            {
                sb.AppendLine("                        if (!matchedExceptionInterceptor)");
                sb.AppendLine("                        {");
                sb.Append("                            unhandledException = ").Append(ExceptionDispatchInfoFullName)
                  .AppendLine(".Capture(exception);");
                sb.AppendLine("                        }");
            }

            EmitChainMerge(sb, plan, "exceptionChain", "exceptionResult", "                        ");
            sb.AppendLine("                    }");
        }
        else if (needsUnhandled)
        {
            sb.AppendLine();
            sb.AppendLine("                    if (exception is not null)");
            sb.AppendLine("                    {");
            sb.Append("                        unhandledException = ").Append(ExceptionDispatchInfoFullName)
              .AppendLine(".Capture(exception);");
            sb.AppendLine("                    }");
        }

        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        EmitFinalCalls(sb, plan, direct, "result", "                    ");
        sb.AppendLine("                }");
        sb.AppendLine();

        if (needsUnhandled)
        {
            sb.AppendLine("                if (unhandledException is not null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    unhandledException.Throw();");
            sb.AppendLine("                }");
            sb.AppendLine();
        }

        sb.AppendLine("                return result;");
    }

    /// <summary>
    ///     Appends a plan's construction-factory argument when one qualifies and the
    ///     referenced surfaces support it: the parameterless <c>new</c> shape first (the
    ///     cheaper one, and available against older packages), the provider-taking shape
    ///     for dependency-injected constructors otherwise — keyed resolutions only when
    ///     the keyed-service extensions are resolvable in the consuming compilation.
    /// </summary>
    private static void AppendPlanFactory(
        StringBuilder sb,
        string handlerTypeExpression,
        bool hasDirectConstruction,
        string? providerConstructionExpression,
        bool usesKeyedServices,
        bool emitPlanFactories,
        bool emitProviderPlanFactories,
        bool hasKeyedServiceExtensions)
    {
        if (emitPlanFactories && hasDirectConstruction)
        {
            sb.Append("static () => new ").Append(handlerTypeExpression).Append("()");
        }
        else if (emitProviderPlanFactories
                 && providerConstructionExpression is not null
                 && (!usesKeyedServices || hasKeyedServiceExtensions))
        {
            sb.Append(providerConstructionExpression);
        }
    }

    /// <summary>
    ///     Emits the keyed registration body shared by the catalog and builder surfaces:
    ///     one guarded block per discovery-key cluster. Messages are named one call each;
    ///     pipeline participants are collected into a local list and registered in one
    ///     batch at the end, unless <paramref name="batchParticipants"/> is off (the
    ///     catalog surface, and older builder packages), in which case every type is named
    ///     through the same per-type call.
    /// </summary>
    private static void EmitKeyedBody(
        StringBuilder sb,
        IReadOnlyList<RegistrableTypeModel> types,
        bool batchParticipants,
        string receiver,
        string registerMethod)
    {
        var emitParticipants = batchParticipants && HasParticipants(types);

        if (emitParticipants)
        {
            sb.AppendLine("            var participants = new global::System.Collections.Generic.List<global::System.Type>();");
            sb.AppendLine();
        }

        var clusters = BuildClusters(types);

        for (var i = 0; i < clusters.Count; i++)
        {
            var cluster = clusters[i];

            if (i > 0)
            {
                sb.AppendLine();
            }

            sb.Append("            if (");

            for (var k = 0; k < cluster.Keys.Count; k++)
            {
                if (k > 0)
                {
                    sb.Append(" || ");
                }

                sb.Append("MatchesDiscoveryKey(")
                  .Append(SymbolDisplay.FormatLiteral(cluster.Keys[k], quote: true))
                  .Append(", discoveryKeyPattern)");
            }

            sb.AppendLine(")");
            sb.AppendLine("            {");

            foreach (var type in cluster.Types)
            {
                if (emitParticipants && type.Descriptors.Length > 0)
                {
                    sb.Append("                participants.Add(typeof(")
                      .Append(type.TypeofExpression).AppendLine("));");
                }
                else
                {
                    sb.Append("                ").Append(receiver)
                      .Append('.').Append(registerMethod)
                      .Append("(typeof(").Append(type.TypeofExpression).AppendLine("));");
                }
            }

            sb.AppendLine("            }");
        }

        if (emitParticipants)
        {
            sb.AppendLine();
            sb.AppendLine("            if (participants.Count > 0)");
            sb.AppendLine("            {");
            sb.Append("                ").Append(receiver).AppendLine(".RegisterParticipants(participants);");
            sb.AppendLine("            }");
        }
    }

    private static void EmitMatchesHelper(StringBuilder sb, ref bool wroteMember)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     Whether a discovery key matches a pattern: ordinal equality, or — when the");
        sb.AppendLine("        ///     pattern ends with <c>*</c> — an ordinal prefix match on the part before the");
        sb.AppendLine("        ///     star. Mirrors the runtime <c>Discovery</c> helper.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static bool MatchesDiscoveryKey(string key, string discoveryKeyPattern)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (discoveryKeyPattern.Length > 0 && discoveryKeyPattern[discoveryKeyPattern.Length - 1] == '*')");
        sb.AppendLine("            {");
        sb.AppendLine("                return key.Length >= discoveryKeyPattern.Length - 1");
        sb.AppendLine("                    && string.CompareOrdinal(key, 0, discoveryKeyPattern, 0, discoveryKeyPattern.Length - 1) == 0;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return string.Equals(key, discoveryKeyPattern, global::System.StringComparison.Ordinal);");
        sb.AppendLine("        }");
    }

    /// <summary>
    ///     A group of types sharing the same effective discovery-key set, emitted under a
    ///     single key-match guard. Untagged types form the default cluster (the implicit
    ///     empty-string key), which sorts first.
    /// </summary>
    private sealed class Cluster
    {
        public Cluster(string signature, List<string> keys)
        {
            Signature = signature;
            Keys = keys;
        }

        public string Signature { get; }

        public List<string> Keys { get; }

        public List<RegistrableTypeModel> Types { get; } = [];
    }

    private static List<Cluster> BuildClusters(IReadOnlyList<RegistrableTypeModel> types)
    {
        var bySignature = new Dictionary<string, Cluster>(StringComparer.Ordinal);
        var clusters = new List<Cluster>();

        foreach (var type in types)
        {
            var keys = EffectiveKeys(type);
            var signature = string.Join("\u001f", keys);

            if (!bySignature.TryGetValue(signature, out var cluster))
            {
                cluster = new Cluster(signature, keys);
                bySignature.Add(signature, cluster);
                clusters.Add(cluster);
            }

            cluster.Types.Add(type);
        }

        // Deterministic block order; the default cluster's empty signature sorts first.
        clusters.Sort(static (x, y) => string.CompareOrdinal(x.Signature, y.Signature));

        return clusters;
    }

    /// <summary>
    ///     The type's effective discovery keys for emission: the implicit default key when
    ///     it declares none, else its declared keys sorted and deduplicated so equivalent
    ///     declarations cluster together.
    /// </summary>
    private static List<string> EffectiveKeys(in RegistrableTypeModel type)
    {
        if (type.DiscoveryKeys.IsEmpty)
        {
            return [""];
        }

        var keys = new List<string>(type.DiscoveryKeys.Length);

        foreach (var key in type.DiscoveryKeys)
        {
            if (!keys.Contains(key))
            {
                keys.Add(key);
            }
        }

        keys.Sort(static (x, y) => string.CompareOrdinal(x, y));

        return keys;
    }

    private static void StartMember(StringBuilder sb, ref bool wroteMember)
    {
        if (wroteMember)
        {
            sb.AppendLine();
        }

        wroteMember = true;
    }
}
