
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Stella.Ergosfare.SourceGenerator.Models;

namespace Stella.Ergosfare.SourceGenerator;

/// <summary>
///     Renders the generated registration source. The emitted code is deliberately
///     conservative C# (block namespace, no target-typed constructs) because it compiles
///     inside the consumer's project under whatever language version they use.
/// </summary>
/// <remarks>
///     Every registration surface comes in two overloads: the pattern-less form selects
///     default discovery (types without a <c>[DiscoveryKey]</c>), while the pattern form
///     cherry-picks keyed types (<c>RegisterGenerated("reporting.*")</c>). Types are
///     emitted in clusters sharing the same discovery-key set, each guarded by a key-match
///     check; the registry's idempotence makes overlapping selections across chained calls
///     safe. Types with pre-computed descriptors register through
///     <c>HandlerDescriptors</c> + <c>RegisterDescriptors</c>, bypassing the reflection
///     based descriptor builders entirely; plain messages and open generic types fall back
///     to direct <c>typeof</c>-based <c>Register</c> calls, which also keep the
///     trimmer/AOT analyzers statically satisfied. When the referenced Ergosfare packages
///     predate the descriptor surface, emission degrades to pure <c>Register(Type)</c>
///     calls.
/// </remarks>
internal static class RegistrationEmitter
{
    private const string RegistryFullName = "global::Stella.Ergosfare.Core.Abstractions.Registry.IMessageRegistry";
    private const string DescriptorFullName = "global::Stella.Ergosfare.Core.Abstractions.Registry.Descriptors.IHandlerDescriptor";
    private const string FactoryFullName = "global::Stella.Ergosfare.Core.Abstractions.Registry.Descriptors.HandlerDescriptors";
    private const string CommandBuilderFullName = "global::Stella.Ergosfare.Commands.Extensions.MicrosoftDependencyInjection.CommandModuleBuilder";
    private const string QueryBuilderFullName = "global::Stella.Ergosfare.Queries.Extensions.MicrosoftDependencyInjection.QueryModuleBuilder";
    private const string EventBuilderFullName = "global::Stella.Ergosfare.Events.Extensions.MicrosoftDependencyInjection.EventModuleBuilder";
    private const string DispatchRootsFullName = "global::Stella.Ergosfare.Core.Abstractions.DispatchRoots.GeneratedDispatchRoots";
    private const string DescriptorCatalogFullName = "global::Stella.Ergosfare.Core.Abstractions.GeneratedDescriptorCatalog";

    /// <summary>
    ///     Emits the <c>ErgosfareGeneratedRegistrations</c> class for the discovered types.
    /// </summary>
    public static string Emit(
        IReadOnlyList<RegistrableTypeModel> types,
        ModuleBuilderAvailability builders,
        IReadOnlyList<VoidPlanModel> voidPlans,
        IReadOnlyList<ResultPlanModel> resultPlans,
        IReadOnlyList<StagedPlanModel> stagedPlans,
        string generatorVersion)
    {
        var useDescriptors = builders.HasDescriptorFactory;
        var emitDispatchRoots = builders.HasDispatchRoots && HasDispatchableMessages(types);
        var sb = new StringBuilder(8192);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Stella.Ergosfare.SourceGenerator — do not edit.");
        sb.AppendLine("// Compile-time replacement for reflection-based assembly scanning (RegisterFromAssembly).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Stella.Ergosfare.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Ergosfare constructs (messages, handlers, interceptors) discovered at compile");
        sb.AppendLine("    ///     time in this compilation and its scanned references. Handler descriptors are");
        sb.AppendLine("    ///     pre-computed, so registration performs no reflection over handler types; plain");
        sb.AppendLine("    ///     messages and open generic types register through the runtime fallback.");
        sb.AppendLine("    ///     Trimmed/AOT builds stay warning-free: every type is referenced statically via");
        sb.AppendLine("    ///     <c>typeof</c>.");
        sb.AppendLine("    /// </summary>");
        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"Stella.Ergosfare.SourceGenerator\", \"")
          .Append(generatorVersion)
          .AppendLine("\")]");
        sb.AppendLine("    internal static class ErgosfareGeneratedRegistrations");
        sb.AppendLine("    {");

        var wroteMember = false;

        if (builders.HasMessageRegistry)
        {
            EmitRegistrySurface(sb, ref wroteMember, types, useDescriptors, emitDispatchRoots);
        }

        if (builders.HasCommandModuleBuilder)
        {
            EmitBuilderSurface(sb, ref wroteMember, CommandBuilderFullName, "command",
                Filter(types, static t => t.IsCommand), useDescriptors && builders.CommandBuilderHasRegisterDescriptors,
                emitDispatchRoots);
        }

        if (builders.HasQueryModuleBuilder)
        {
            EmitBuilderSurface(sb, ref wroteMember, QueryBuilderFullName, "query",
                Filter(types, static t => t.IsQuery), useDescriptors && builders.QueryBuilderHasRegisterDescriptors,
                emitDispatchRoots);
        }

        if (builders.HasEventModuleBuilder)
        {
            EmitBuilderSurface(sb, ref wroteMember, EventBuilderFullName, "event",
                Filter(types, static t => t.IsEvent), useDescriptors && builders.EventBuilderHasRegisterDescriptors,
                emitDispatchRoots);
        }

        if (emitDispatchRoots)
        {
            EmitDispatchRoots(sb, ref wroteMember, types, voidPlans, resultPlans, stagedPlans,
                builders.DispatchRootsHasPlanFactories,
                builders.DispatchRootsHasProviderPlanFactories,
                builders.HasKeyedServiceExtensions);

            EmitStagedPlanClasses(sb, ref wroteMember, stagedPlans, builders.StagedPlansSupportDirectConstruction);
        }

        if (builders.HasDescriptorCatalog && useDescriptors && HasDescriptors(types))
        {
            EmitDescriptorCatalog(sb, ref wroteMember, types);
        }

        EmitMatchesHelper(sb, ref wroteMember);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static List<RegistrableTypeModel> Filter(
        IReadOnlyList<RegistrableTypeModel> types,
        Func<RegistrableTypeModel, bool> predicate)
    {
        var filtered = new List<RegistrableTypeModel>(types.Count);

        foreach (var type in types)
        {
            if (predicate(type))
            {
                filtered.Add(type);
            }
        }

        return filtered;
    }

    private static bool HasDescriptors(IReadOnlyList<RegistrableTypeModel> types)
    {
        foreach (var type in types)
        {
            if (type.Descriptors.Length > 0)
            {
                return true;
            }
        }

        return false;
    }

    private static bool HasDispatchableMessages(IReadOnlyList<RegistrableTypeModel> types)
    {
        foreach (var type in types)
        {
            if (type.IsDispatchableMessage)
            {
                return true;
            }
        }

        return false;
    }

    private static void EmitRegistrySurface(
        StringBuilder sb,
        ref bool wroteMember,
        IReadOnlyList<RegistrableTypeModel> types,
        bool useDescriptors,
        bool emitDispatchRoots)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     Registers every discovered construct that participates in default discovery");
        sb.AppendLine("        ///     (no <c>[DiscoveryKey]</c>) into the given registry, regardless of module.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static void RegisterAll(").Append(RegistryFullName).AppendLine(" registry)");
        sb.AppendLine("        {");
        sb.AppendLine("            RegisterAll(registry, \"\");");
        sb.AppendLine("        }");

        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     Registers every discovered construct whose discovery keys match the given");
        sb.AppendLine("        ///     pattern — an exact key or a trailing-<c>*</c> prefix glob — regardless of");
        sb.AppendLine("        ///     module. Chained calls with overlapping patterns are safe: the registry is");
        sb.AppendLine("        ///     idempotent per handler type.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static void RegisterAll(").Append(RegistryFullName).AppendLine(" registry, string discoveryKeyPattern)");
        sb.AppendLine("        {");

        if (emitDispatchRoots)
        {
            sb.AppendLine("            RootDispatchInstantiations();");
            sb.AppendLine();
        }

        EmitKeyedBody(sb, types, useDescriptors, "registry");
        sb.AppendLine("        }");
    }

    private static void EmitBuilderSurface(
        StringBuilder sb,
        ref bool wroteMember,
        string builderFullName,
        string moduleName,
        List<RegistrableTypeModel> moduleTypes,
        bool useDescriptors,
        bool emitDispatchRoots)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.Append("        ///     Registers every discovered ").Append(moduleName).AppendLine("-module construct that participates");
        sb.AppendLine("        ///     in default discovery (no <c>[DiscoveryKey]</c>). Drop-in replacement for");
        sb.AppendLine("        ///     <c>RegisterFromAssembly</c>.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static ").Append(builderFullName).AppendLine(" RegisterGenerated(");
        sb.Append("            this ").Append(builderFullName).AppendLine(" builder)");
        sb.AppendLine("        {");
        sb.AppendLine("            return RegisterGenerated(builder, \"\");");
        sb.AppendLine("        }");

        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.Append("        ///     Registers every discovered ").Append(moduleName).AppendLine("-module construct whose discovery");
        sb.AppendLine("        ///     keys match the given pattern — an exact key or a trailing-<c>*</c> prefix");
        sb.AppendLine("        ///     glob. Chain calls to compose selections; overlapping patterns are safe.");
        sb.AppendLine("        /// </summary>");
        sb.Append("        public static ").Append(builderFullName).AppendLine(" RegisterGenerated(");
        sb.Append("            this ").Append(builderFullName).AppendLine(" builder, string discoveryKeyPattern)");
        sb.AppendLine("        {");

        if (emitDispatchRoots)
        {
            sb.AppendLine("            RootDispatchInstantiations();");
            sb.AppendLine();
        }

        EmitKeyedBody(sb, moduleTypes, useDescriptors, "builder");
        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
    }

    /// <summary>
    ///     Emits the dispatch-root method: one <c>AddMessage</c> per dispatchable message
    ///     plus <c>AddResult</c>/<c>AddStream</c> per closed result contract. The generic
    ///     closures let the runtime's dispatch caches construct their executors and
    ///     invokers without <c>MakeGenericType</c> and give Native AOT a static anchor for
    ///     every instantiation. Additions are idempotent, so every registration surface
    ///     calls this unconditionally.
    /// </summary>
    private static void EmitDispatchRoots(
        StringBuilder sb,
        ref bool wroteMember,
        IReadOnlyList<RegistrableTypeModel> types,
        IReadOnlyList<VoidPlanModel> voidPlans,
        IReadOnlyList<ResultPlanModel> resultPlans,
        IReadOnlyList<StagedPlanModel> stagedPlans,
        bool emitPlanFactories,
        bool emitProviderPlanFactories,
        bool hasKeyedServiceExtensions)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        private static void RootDispatchInstantiations()");
        sb.AppendLine("        {");

        foreach (var type in types)
        {
            if (!type.IsDispatchableMessage)
            {
                continue;
            }

            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(".AddMessage<").Append(type.TypeofExpression).AppendLine(">();");

            foreach (var result in type.DispatchResults)
            {
                sb.Append("            ").Append(DispatchRootsFullName)
                  .Append(result.IsStream ? ".AddStream<" : ".AddResult<")
                  .Append(type.TypeofExpression).Append(", ").Append(result.ResultTypeExpression)
                  .AppendLine(">();");
            }
        }

        // Compile-time pipeline plans: the runtime re-validates each one against the
        // registry per version, so a plan can only lose its speedup, never change
        // behavior. Qualifying handlers additionally carry a construction factory —
        // parameterless `new` or a provider-taking one for dependency-injected
        // constructors — which the runtime uses only after verifying the handler's
        // effective DI registration is the module's own plain transient one.
        foreach (var plan in voidPlans)
        {
            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(".AddVoidPlan<").Append(plan.MessageTypeExpression)
              .Append(", ").Append(plan.HandlerTypeExpression)
              .Append(">(");

            AppendPlanFactory(sb, plan.HandlerTypeExpression, plan.HasDirectConstruction,
                plan.ProviderConstructionExpression, plan.UsesKeyedServices,
                emitPlanFactories, emitProviderPlanFactories, hasKeyedServiceExtensions);

            sb.AppendLine(");");
        }

        foreach (var plan in resultPlans)
        {
            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(".AddResultPlan<").Append(plan.MessageTypeExpression)
              .Append(", ").Append(plan.ResultTypeExpression)
              .Append(", ").Append(plan.HandlerTypeExpression)
              .Append(">(");

            AppendPlanFactory(sb, plan.HandlerTypeExpression, plan.HasDirectConstruction,
                plan.ProviderConstructionExpression, plan.UsesKeyedServices,
                emitPlanFactories, emitProviderPlanFactories, hasKeyedServiceExtensions);

            sb.AppendLine(");");
        }

        // Staged plans: bespoke straight-line pipelines for interceptor-bearing messages,
        // emitted as sealed plan classes below. Advisory like every plan — the hosting
        // executor re-validates the baked composition per registry version.
        for (var i = 0; i < stagedPlans.Count; i++)
        {
            var plan = stagedPlans[i];

            sb.Append("            ").Append(DispatchRootsFullName)
              .Append(".AddStagedPlan<").Append(plan.MessageTypeExpression);

            if (plan.ResultTypeExpression is not null)
            {
                sb.Append(", ").Append(plan.ResultTypeExpression);
            }

            sb.Append(">(new StagedPlan").Append(i).AppendLine("());");
        }

        sb.AppendLine("        }");
    }

    private const string HandlersNamespace = "global::Stella.Ergosfare.Core.Abstractions.Handlers.";
    private const string StagedCompositionFullName = "global::Stella.Ergosfare.Core.Abstractions.StagedPlans.StagedPlanComposition";
    private const string ExecutionContextFullName = "global::Stella.Ergosfare.Core.Abstractions.IExecutionContext";
    private const string AbortedExceptionFullName = "global::Stella.Ergosfare.Core.Abstractions.Exceptions.ExecutionAbortedException";
    private const string ValueTaskFullName = "global::System.Threading.Tasks.ValueTask";
    private const string GetRequiredServiceFullName = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";

    /// <summary>
    ///     Emits one sealed plan class per staged plan: the baked composition plus a
    ///     bespoke <c>Execute</c> reproducing the runtime strategy's semantics exactly for
    ///     the baked pipeline — pre stages in order (each may rewrite the message), the
    ///     handler, post stages with result rewrite, exception stages (skipped for
    ///     <c>ExecutionAbortedException</c>, swallowing the exception once they ran, like
    ///     the strategy), and final stages that always run. Casts mirror the strategy and
    ///     invoker code shapes, including the erased-generic unbox semantics for
    ///     value-typed results. Participants resolve from the dispatching provider — what
    ///     the runtime references do outside memoized mode, which the hosting executor's
    ///     gate excludes.
    /// </summary>
    private static void EmitStagedPlanClasses(
        StringBuilder sb,
        ref bool wroteMember,
        IReadOnlyList<StagedPlanModel> stagedPlans,
        bool supportsDirectConstruction)
    {
        for (var i = 0; i < stagedPlans.Count; i++)
        {
            var plan = stagedPlans[i];
            var isVoid = plan.ResultTypeExpression is null;
            var emitDirect = supportsDirectConstruction && plan.SupportsDirectConstruction;

            StartMember(sb, ref wroteMember);
            sb.Append("        private sealed class StagedPlan").Append(i).Append(" : global::Stella.Ergosfare.Core.Abstractions.StagedPlans.");

            if (isVoid)
            {
                sb.Append("StagedVoidPlan<").Append(plan.MessageTypeExpression).AppendLine(">");
            }
            else
            {
                sb.Append("StagedResultPlan<").Append(plan.MessageTypeExpression)
                  .Append(", ").Append(plan.ResultTypeExpression).AppendLine(">");
            }

            sb.AppendLine("        {");

            if (isVoid)
            {
                sb.Append("            private static readonly object CompletedVoidResult = default(")
                  .Append(ValueTaskFullName).AppendLine(");");
                sb.AppendLine();
            }

            sb.Append("            private static readonly ").Append(StagedCompositionFullName)
              .Append(" BakedComposition = new ").Append(StagedCompositionFullName).AppendLine("(");
            sb.Append("                typeof(").Append(plan.HandlerTypeExpression).AppendLine("),");
            AppendCompositionStage(sb, plan.PreCalls);
            sb.AppendLine(",");
            AppendCompositionStage(sb, plan.PostCalls);
            sb.AppendLine(",");
            AppendCompositionStage(sb, plan.ExceptionCalls);
            sb.AppendLine(",");
            AppendCompositionStage(sb, plan.FinalCalls);
            sb.AppendLine(");");
            sb.AppendLine();
            sb.Append("            public override ").Append(StagedCompositionFullName).AppendLine(" Composition");
            sb.AppendLine("            {");
            sb.AppendLine("                get { return BakedComposition; }");
            sb.AppendLine("            }");
            sb.AppendLine();

            sb.Append("            public override async ").Append(ValueTaskFullName);

            if (!isVoid)
            {
                sb.Append('<').Append(plan.ResultTypeExpression).Append('>');
            }

            sb.AppendLine(" Execute(");
            sb.Append("                ").Append(plan.MessageTypeExpression).AppendLine(" message,");
            sb.Append("                ").Append(ExecutionContextFullName).AppendLine(" context,");
            sb.AppendLine("                global::System.IServiceProvider serviceProvider)");
            sb.AppendLine("            {");

            if (isVoid)
            {
                EmitVoidExecuteBody(sb, plan, direct: false);
            }
            else
            {
                EmitResultExecuteBody(sb, plan, direct: false);
            }

            sb.AppendLine("            }");

            // The direct-construction variant: the same pipeline with every participant
            // constructed via `new` — used by the hosting executor only after it verified
            // every participant's plain transient registration.
            if (emitDirect)
            {
                sb.AppendLine();
                sb.AppendLine("            public override bool SupportsDirectConstruction");
                sb.AppendLine("            {");
                sb.AppendLine("                get { return true; }");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.Append("            public override async ").Append(ValueTaskFullName);

                if (!isVoid)
                {
                    sb.Append('<').Append(plan.ResultTypeExpression).Append('>');
                }

                sb.AppendLine(" ExecuteDirect(");
                sb.Append("                ").Append(plan.MessageTypeExpression).AppendLine(" message,");
                sb.Append("                ").Append(ExecutionContextFullName).AppendLine(" context,");
                sb.AppendLine("                global::System.IServiceProvider serviceProvider)");
                sb.AppendLine("            {");

                if (isVoid)
                {
                    EmitVoidExecuteBody(sb, plan, direct: true);
                }
                else
                {
                    EmitResultExecuteBody(sb, plan, direct: true);
                }

                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
        }
    }

    private static void AppendCompositionStage(StringBuilder sb, System.Collections.Immutable.ImmutableArray<StagedCallModel> calls)
    {
        if (calls.IsEmpty)
        {
            sb.Append("                global::System.Array.Empty<global::System.Type>()");
            return;
        }

        sb.Append("                new global::System.Type[] { ");

        for (var i = 0; i < calls.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append("typeof(").Append(calls[i].TypeExpression).Append(')');
        }

        sb.Append(" }");
    }

    private static void AppendResolve(StringBuilder sb, string typeExpression)
        => sb.Append(GetRequiredServiceFullName).Append('<').Append(typeExpression).Append(">(serviceProvider)");

    /// <summary>
    ///     A participant expression: the container resolution, or — in the
    ///     direct-construction variant — the participant's <c>new</c> expression.
    /// </summary>
    private static void AppendParticipant(StringBuilder sb, string typeExpression, string? constructionExpression)
    {
        if (constructionExpression is null)
        {
            AppendResolve(sb, typeExpression);
        }
        else
        {
            sb.Append(constructionExpression);
        }
    }

    /// <summary>
    ///     The strategy/invoker-parity cast of the chained object result back to the
    ///     pipeline result type.
    /// </summary>
    /// <param name="targetAcceptsNull">
    ///     Whether the stage being called declares its result parameter as
    ///     <c>TResult?</c>. Exception and final interceptors do; post interceptors declare
    ///     a plain <c>TResult</c>. The distinction is load-bearing for reference-typed
    ///     results: a cast to <c>TResult?</c> resets the expression's nullable state to
    ///     maybe-null however non-null the chain variable is, so handing one to a post
    ///     interceptor is CS8604 in the consumer's build — and a build failure outright
    ///     where warnings are errors.
    /// </param>
    private static string ResultCast(string resultExpression, bool resultIsValueType, bool targetAcceptsNull, string operand)
        => resultIsValueType
            ? "(" + resultExpression + ")" + operand + "!"
            : targetAcceptsNull
                ? "(" + resultExpression + "?)" + operand
                : "(" + resultExpression + ")" + operand;

    private static void EmitPreCalls(StringBuilder sb, StagedPlanModel plan, bool direct, string indent)
    {
        foreach (var call in plan.PreCalls)
        {
            sb.Append(indent).Append("message = (").Append(plan.MessageTypeExpression).Append(") ");

            if (call.Arm == StagedCallArm.Sync)
            {
                sb.Append("((").Append(HandlersNamespace).Append("IPreInterceptor<").Append(plan.MessageTypeExpression).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.AppendLine(").Handle(message, context);");
            }
            else
            {
                sb.Append("await ((").Append(HandlersNamespace).Append("IAsyncPreInterceptor<").Append(plan.MessageTypeExpression).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.AppendLine(").HandleAsync(message, context);");
            }
        }
    }

    /// <summary>
    ///     Emits one interceptor-chain call for a result-carrying stage, rewriting the
    ///     given object-typed chain variable exactly as the runtime invoker loop does.
    /// </summary>
    private static void EmitChainCall(
        StringBuilder sb,
        StagedPlanModel plan,
        StagedCallModel call,
        bool direct,
        string stageInterface,
        string chainVariable,
        string? exceptionArgument,
        string indent)
    {
        var pipelineResult = plan.ResultTypeExpression ?? ValueTaskFullName;
        var pipelineResultIsValueType = plan.ResultTypeExpression is null || plan.ResultIsValueType;
        var extraArgument = exceptionArgument is null ? string.Empty : ", " + exceptionArgument;

        // The exception argument doubles as the stage discriminator: only the exception
        // stage carries one, and only the exception stage declares its result parameter
        // nullable. The post stage takes TResult and object, not TResult? and object?.
        var targetAcceptsNull = exceptionArgument is not null;

        sb.Append(indent).Append(chainVariable).Append(" = ");

        switch (call.Arm)
        {
            case StagedCallArm.AsyncTyped:
                sb.Append("await ((").Append(HandlersNamespace).Append("IAsync").Append(stageInterface)
                  .Append('<').Append(plan.MessageTypeExpression).Append(", ").Append(pipelineResult).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.Append(").HandleAsync(message, ")
                  .Append(ResultCast(pipelineResult, pipelineResultIsValueType, targetAcceptsNull, chainVariable))
                  .Append(extraArgument).AppendLine(", context);");
                break;
            case StagedCallArm.AsyncAgnostic:
                sb.Append("await ((").Append(HandlersNamespace).Append("IAsync").Append(stageInterface)
                  .Append('<').Append(plan.MessageTypeExpression).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.Append(").HandleAsync(message, ").Append(chainVariable)
                  .Append(exceptionArgument is null ? "!" : string.Empty)
                  .Append(extraArgument).AppendLine(", context);");
                break;
            default:
                sb.Append("((").Append(HandlersNamespace).Append('I').Append(stageInterface)
                  .Append('<').Append(plan.MessageTypeExpression).Append(", ").Append(pipelineResult).Append(">)");
                AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                sb.Append(").Handle(message, ")
                  .Append(ResultCast(pipelineResult, pipelineResultIsValueType, targetAcceptsNull, chainVariable))
                  .Append(extraArgument).AppendLine(", context);");
                break;
        }
    }

    private static void EmitFinalCalls(StringBuilder sb, StagedPlanModel plan, bool direct, string resultExpressionText, string indent)
    {
        var pipelineResult = plan.ResultTypeExpression ?? ValueTaskFullName;
        var pipelineResultIsValueType = plan.ResultTypeExpression is null || plan.ResultIsValueType;

        // Final interceptors declare `TResult? result` — the stage runs from a finally,
        // so the pipeline may never have produced one.
        const bool targetAcceptsNull = true;

        foreach (var call in plan.FinalCalls)
        {
            switch (call.Arm)
            {
                case StagedCallArm.AsyncTyped:
                    sb.Append(indent).Append("await ((").Append(HandlersNamespace).Append("IAsyncFinalInterceptor<")
                      .Append(plan.MessageTypeExpression).Append(", ").Append(pipelineResult).Append(">)");
                    AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                    sb.Append(").HandleAsync(message, ")
                      .Append(ResultCast(pipelineResult, pipelineResultIsValueType, targetAcceptsNull, resultExpressionText))
                      .AppendLine(", exception, context);");
                    break;
                case StagedCallArm.AsyncAgnostic:
                    sb.Append(indent).Append("await ((").Append(HandlersNamespace).Append("IAsyncFinalInterceptor<")
                      .Append(plan.MessageTypeExpression).Append(">)");
                    AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                    sb.Append(").HandleAsync(message, ").Append(resultExpressionText).AppendLine(", exception, context);");
                    break;
                default:
                    sb.Append(indent).Append("((").Append(HandlersNamespace).Append("IFinalInterceptor<")
                      .Append(plan.MessageTypeExpression).Append(", ").Append(pipelineResult).Append(">)");
                    AppendParticipant(sb, call.TypeExpression, direct ? call.ConstructionExpression : null);
                    sb.Append(").Handle(message, ")
                      .Append(ResultCast(pipelineResult, pipelineResultIsValueType, targetAcceptsNull, resultExpressionText))
                      .AppendLine(", exception, context);");
                    break;
            }
        }
    }

    private static void EmitVoidExecuteBody(StringBuilder sb, StagedPlanModel plan, bool direct)
    {
        var needsResult = !plan.PostCalls.IsEmpty || !plan.ExceptionCalls.IsEmpty || !plan.FinalCalls.IsEmpty;
        var needsGuards = needsResult;

        if (!needsGuards)
        {
            // Pre-only pipeline: with zero exception and final stages the strategy's
            // try/catch/finally is a no-op shell — exceptions propagate unchanged.
            EmitPreCalls(sb, plan, direct, "                ");
            sb.Append("                await ");
            AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
            sb.AppendLine(".HandleAsync(message, context);");
            return;
        }

        sb.AppendLine("                object? result = null;");
        sb.AppendLine("                global::System.Exception? exception = null;");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        EmitPreCalls(sb, plan, direct, "                    ");
        sb.Append("                    await ");
        AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
        sb.AppendLine(".HandleAsync(message, context);");
        sb.AppendLine("                    result = CompletedVoidResult;");

        if (!plan.PostCalls.IsEmpty)
        {
            foreach (var call in plan.PostCalls)
            {
                EmitChainCall(sb, plan, call, direct, "PostInterceptor", "result", null, "                    ");
            }

            // The strategy's post epilogue: a null post result restores the completed
            // task; anything non-ValueTask fails the closed nullable cast, exactly like
            // the strategy's own cast would.
            sb.Append("                    var invokedPostResult = (").Append(ValueTaskFullName).AppendLine("?) result;");
            sb.AppendLine("                    result = invokedPostResult == null ? CompletedVoidResult : result;");
        }

        sb.AppendLine("                }");
        sb.Append("                catch (global::System.Exception e) when (e is not ").Append(AbortedExceptionFullName).AppendLine(")");
        sb.AppendLine("                {");
        sb.AppendLine("                    exception = e;");

        if (plan.ExceptionCalls.IsEmpty)
        {
            sb.AppendLine("                    throw;");
        }
        else
        {
            sb.AppendLine("                    var resultBeforeExceptions = result;");

            foreach (var call in plan.ExceptionCalls)
            {
                EmitChainCall(sb, plan, call, direct, "ExceptionInterceptor", "result", "e", "                    ");
            }

            sb.Append("                    var invokedExceptionResult = (").Append(ValueTaskFullName).AppendLine("?) result;");
            sb.AppendLine("                    result = invokedExceptionResult == null ? resultBeforeExceptions : result;");
        }

        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        EmitFinalCalls(sb, plan, direct, "result", "                    ");
        sb.AppendLine("                }");
    }

    private static void EmitResultExecuteBody(StringBuilder sb, StagedPlanModel plan, bool direct)
    {
        var resultExpression = plan.ResultTypeExpression!;
        var needsGuards = !plan.PostCalls.IsEmpty || !plan.ExceptionCalls.IsEmpty || !plan.FinalCalls.IsEmpty;

        if (!needsGuards)
        {
            EmitPreCalls(sb, plan, direct, "                ");
            sb.Append("                return await ");
            AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
            sb.AppendLine(".HandleAsync(message, context);");
            return;
        }

        sb.Append("                ").Append(resultExpression).AppendLine(" result = default!;");
        sb.AppendLine("                global::System.Exception? exception = null;");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        EmitPreCalls(sb, plan, direct, "                    ");
        sb.Append("                    result = await ");
        AppendParticipant(sb, plan.HandlerTypeExpression, direct ? plan.HandlerConstructionExpression : null);
        sb.AppendLine(".HandleAsync(message, context);");

        if (!plan.PostCalls.IsEmpty)
        {
            sb.AppendLine("                    object? postChain = result;");

            foreach (var call in plan.PostCalls)
            {
                EmitChainCall(sb, plan, call, direct, "PostInterceptor", "postChain", null, "                    ");
            }

            if (plan.ResultIsValueType)
            {
                // The strategy's erased (TResult?) cast is a plain unbox for value-typed
                // results — a null post result throws there, so no null branch exists.
                sb.Append("                    result = (").Append(resultExpression).AppendLine(") postChain!;");
            }
            else
            {
                sb.Append("                    var postResult = (").Append(resultExpression).AppendLine("?) postChain;");
                sb.AppendLine("                    result = postResult == null ? result : postResult;");
            }
        }

        sb.AppendLine("                }");
        sb.Append("                catch (global::System.Exception e) when (e is not ").Append(AbortedExceptionFullName).AppendLine(")");
        sb.AppendLine("                {");
        sb.AppendLine("                    exception = e;");

        if (plan.ExceptionCalls.IsEmpty)
        {
            sb.AppendLine("                    throw;");
        }
        else
        {
            sb.AppendLine("                    object? exceptionChain = result;");

            foreach (var call in plan.ExceptionCalls)
            {
                EmitChainCall(sb, plan, call, direct, "ExceptionInterceptor", "exceptionChain", "e", "                    ");
            }

            if (plan.ResultIsValueType)
            {
                sb.Append("                    result = (").Append(resultExpression).AppendLine(") exceptionChain!;");
            }
            else
            {
                sb.Append("                    var exceptionResult = (").Append(resultExpression).AppendLine("?) exceptionChain;");
                sb.AppendLine("                    result = exceptionResult == null ? result : exceptionResult;");
            }
        }

        sb.AppendLine("                }");
        sb.AppendLine("                finally");
        sb.AppendLine("                {");
        EmitFinalCalls(sb, plan, direct, "result", "                    ");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                return result;");
    }

    /// <summary>
    ///     Appends a plan's construction-factory argument when one qualifies and the
    ///     referenced surfaces support it: the parameterless <c>new</c> shape first (the
    ///     cheaper one, and available against older packages), the provider-taking shape
    ///     for dependency-injected constructors otherwise — keyed resolutions only when
    ///     the keyed-service extensions are resolvable in the consuming compilation.
    /// </summary>
    private static void AppendPlanFactory(
        StringBuilder sb,
        string handlerTypeExpression,
        bool hasDirectConstruction,
        string? providerConstructionExpression,
        bool usesKeyedServices,
        bool emitPlanFactories,
        bool emitProviderPlanFactories,
        bool hasKeyedServiceExtensions)
    {
        if (emitPlanFactories && hasDirectConstruction)
        {
            sb.Append("static () => new ").Append(handlerTypeExpression).Append("()");
        }
        else if (emitProviderPlanFactories
                 && providerConstructionExpression is not null
                 && (!usesKeyedServices || hasKeyedServiceExtensions))
        {
            sb.Append(providerConstructionExpression);
        }
    }

    /// <summary>
    ///     Emits the keyed registration body shared by the registry and builder surfaces:
    ///     one guarded block per discovery-key cluster, adding descriptors to a local list
    ///     (registered in one call at the end) and issuing runtime-fallback
    ///     <c>Register(typeof)</c> calls inline.
    /// </summary>
    private static void EmitKeyedBody(
        StringBuilder sb,
        IReadOnlyList<RegistrableTypeModel> types,
        bool useDescriptors,
        string receiver)
    {
        var emitDescriptors = useDescriptors && HasDescriptors(types);

        if (emitDescriptors)
        {
            sb.Append("            var descriptors = new global::System.Collections.Generic.List<")
              .Append(DescriptorFullName).AppendLine(">();");
            sb.AppendLine();
        }

        var clusters = BuildClusters(types);

        for (var i = 0; i < clusters.Count; i++)
        {
            var cluster = clusters[i];

            if (i > 0)
            {
                sb.AppendLine();
            }

            sb.Append("            if (");

            for (var k = 0; k < cluster.Keys.Count; k++)
            {
                if (k > 0)
                {
                    sb.Append(" || ");
                }

                sb.Append("MatchesDiscoveryKey(")
                  .Append(SymbolDisplay.FormatLiteral(cluster.Keys[k], quote: true))
                  .Append(", discoveryKeyPattern)");
            }

            sb.AppendLine(")");
            sb.AppendLine("            {");

            foreach (var type in cluster.Types)
            {
                if (useDescriptors && type.Descriptors.Length > 0)
                {
                    foreach (var descriptor in type.Descriptors)
                    {
                        sb.Append("                descriptors.Add(");
                        AppendDescriptorExpression(sb, type, descriptor);
                        sb.AppendLine(");");
                    }
                }
                else
                {
                    sb.Append("                ").Append(receiver)
                      .Append(".Register(typeof(").Append(type.TypeofExpression).AppendLine("));");
                }
            }

            sb.AppendLine("            }");
        }

        if (emitDescriptors)
        {
            sb.AppendLine();
            sb.AppendLine("            if (descriptors.Count > 0)");
            sb.AppendLine("            {");
            sb.Append("                ").Append(receiver).AppendLine(".RegisterDescriptors(descriptors);");
            sb.AppendLine("            }");
        }
    }

    /// <summary>
    ///     Emits the module initializer that hands every modeled handler type's
    ///     compile-time descriptor factory to <c>GeneratedDescriptorCatalog</c>: from then
    ///     on a manual <c>Register&lt;THandler&gt;()</c> — including ones that never call
    ///     <c>RegisterGenerated()</c> — registers without reflection. Purely a lookup
    ///     contribution: nothing is registered here, so initialization order and
    ///     discovery-key gating are unaffected.
    /// </summary>
    private static void EmitDescriptorCatalog(
        StringBuilder sb,
        ref bool wroteMember,
        IReadOnlyList<RegistrableTypeModel> types)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void PopulateDescriptorCatalog()");
        sb.AppendLine("        {");

        foreach (var type in types)
        {
            if (type.Descriptors.Length == 0)
            {
                continue;
            }

            sb.Append("            ").Append(DescriptorCatalogFullName)
              .Append(".Add(typeof(").Append(type.TypeofExpression)
              .Append("), static () => new global::System.Collections.Generic.List<")
              .Append(DescriptorFullName).Append("> { ");

            for (var i = 0; i < type.Descriptors.Length; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }

                AppendDescriptorExpression(sb, type, type.Descriptors[i]);
            }

            sb.AppendLine(" });");
        }

        sb.AppendLine("        }");
    }

    private static void AppendDescriptorExpression(StringBuilder sb, in RegistrableTypeModel type, in DescriptorModel descriptor)
    {
        var factoryMethod = descriptor.Kind switch
        {
            DescriptorKind.MainHandler => "Handler",
            DescriptorKind.PreInterceptor => "PreInterceptor",
            DescriptorKind.PostInterceptor => "PostInterceptor",
            DescriptorKind.ExceptionInterceptor => "ExceptionInterceptor",
            DescriptorKind.FinalInterceptor => "FinalInterceptor",
            _ => "Handler",
        };

        sb.Append(FactoryFullName).Append('.').Append(factoryMethod)
          .Append("(typeof(").Append(descriptor.MessageTypeExpression).Append(')');

        if (descriptor.ResultTypeExpression is not null)
        {
            sb.Append(", typeof(").Append(descriptor.ResultTypeExpression).Append(')');
        }

        sb.Append(", typeof(").Append(type.TypeofExpression).Append(')');

        // Weight and groups are trailing optional parameters; emit them only when they
        // deviate from the factory defaults (weight 0, default group).
        if (type.Weight != 0 || type.GroupsExpression is not null)
        {
            sb.Append(", ").Append(type.Weight).Append('u');
        }

        if (type.GroupsExpression is not null)
        {
            sb.Append(", ").Append(type.GroupsExpression);
        }

        sb.Append(')');
    }

    private static void EmitMatchesHelper(StringBuilder sb, ref bool wroteMember)
    {
        StartMember(sb, ref wroteMember);
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        ///     Whether a discovery key matches a pattern: ordinal equality, or — when the");
        sb.AppendLine("        ///     pattern ends with <c>*</c> — an ordinal prefix match on the part before the");
        sb.AppendLine("        ///     star. Mirrors the runtime <c>Discovery</c> helper.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static bool MatchesDiscoveryKey(string key, string discoveryKeyPattern)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (discoveryKeyPattern.Length > 0 && discoveryKeyPattern[discoveryKeyPattern.Length - 1] == '*')");
        sb.AppendLine("            {");
        sb.AppendLine("                return key.Length >= discoveryKeyPattern.Length - 1");
        sb.AppendLine("                    && string.CompareOrdinal(key, 0, discoveryKeyPattern, 0, discoveryKeyPattern.Length - 1) == 0;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return string.Equals(key, discoveryKeyPattern, global::System.StringComparison.Ordinal);");
        sb.AppendLine("        }");
    }

    /// <summary>
    ///     A group of types sharing the same effective discovery-key set, emitted under a
    ///     single key-match guard. Untagged types form the default cluster (the implicit
    ///     empty-string key), which sorts first.
    /// </summary>
    private sealed class Cluster
    {
        public Cluster(string signature, List<string> keys)
        {
            Signature = signature;
            Keys = keys;
        }

        public string Signature { get; }

        public List<string> Keys { get; }

        public List<RegistrableTypeModel> Types { get; } = [];
    }

    private static List<Cluster> BuildClusters(IReadOnlyList<RegistrableTypeModel> types)
    {
        var bySignature = new Dictionary<string, Cluster>(StringComparer.Ordinal);
        var clusters = new List<Cluster>();

        foreach (var type in types)
        {
            var keys = EffectiveKeys(type);
            var signature = string.Join("\u001f", keys);

            if (!bySignature.TryGetValue(signature, out var cluster))
            {
                cluster = new Cluster(signature, keys);
                bySignature.Add(signature, cluster);
                clusters.Add(cluster);
            }

            cluster.Types.Add(type);
        }

        // Deterministic block order; the default cluster's empty signature sorts first.
        clusters.Sort(static (x, y) => string.CompareOrdinal(x.Signature, y.Signature));

        return clusters;
    }

    /// <summary>
    ///     The type's effective discovery keys for emission: the implicit default key when
    ///     it declares none, else its declared keys sorted and deduplicated so equivalent
    ///     declarations cluster together.
    /// </summary>
    private static List<string> EffectiveKeys(in RegistrableTypeModel type)
    {
        if (type.DiscoveryKeys.IsEmpty)
        {
            return [""];
        }

        var keys = new List<string>(type.DiscoveryKeys.Length);

        foreach (var key in type.DiscoveryKeys)
        {
            if (!keys.Contains(key))
            {
                keys.Add(key);
            }
        }

        keys.Sort(static (x, y) => string.CompareOrdinal(x, y));

        return keys;
    }

    private static void StartMember(StringBuilder sb, ref bool wroteMember)
    {
        if (wroteMember)
        {
            sb.AppendLine();
        }

        wroteMember = true;
    }
}
