using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Stella.Ergosfare.Plugins.Outbox.Generators;

/// <summary>Emits JSON codecs directly; it does not chain the System.Text.Json generator.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class OutboxMessageGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Stella.Ergosfare.Plugins.Outbox.OutboxMessageAttribute";
    private static readonly DiagnosticDescriptor Unsupported = new(
        "OUTBOX001", "Unsupported outbox message", "Cannot generate outbox message '{0}': {1}",
        "Outbox", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor Duplicate = new(
        "OUTBOX002", "Duplicate outbox contract", "Outbox contract '{0}' is declared by more than one message",
        "Outbox", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var messages = context.SyntaxProvider.ForAttributeWithMetadataName(AttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol).Collect();
        context.RegisterSourceOutput(messages, static (output, types) => Emit(output, types));
        var imports = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.SourceModule.ReferencedAssemblySymbols.SelectMany(assembly => assembly.GetAttributes())
                .Where(attribute => attribute.AttributeClass?.ToDisplayString()
                    == "Stella.Ergosfare.Plugins.Outbox.OutboxCodecManifestAttribute")
                .Select(attribute => attribute.ConstructorArguments.FirstOrDefault().Value as INamedTypeSymbol)
                .Where(type => type is not null)
                .Select(type => TypeName(type!)).Distinct().OrderBy(name => name, StringComparer.Ordinal).ToImmutableArray());
        context.RegisterSourceOutput(imports, static (output, names) =>
        {
            if (names.IsEmpty) return;
            var source = new StringBuilder("// <auto-generated/>\nnamespace Stella.Ergosfare.Plugins.Outbox.Generated { internal static class ImportedOutboxCodecs {\n[global::System.Runtime.CompilerServices.ModuleInitializer] internal static void Initialize() {\n");
            foreach (var name in names) source.AppendLine(name + ".Register();");
            source.AppendLine("} } }");
            output.AddSource("ImportedOutboxCodecs.g.cs", source.ToString());
        });
    }

    private static void Emit(SourceProductionContext output, ImmutableArray<INamedTypeSymbol> types)
    {
        var contracts = new HashSet<string>(StringComparer.Ordinal);
        var seen = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
        var index = 0;
        foreach (var type in types.OrderBy(t => t.ToDisplayString(), StringComparer.Ordinal))
        {
            if (!seen.Add(type)) continue;
            output.CancellationToken.ThrowIfCancellationRequested();
            var attribute = type.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == AttributeName);
            var contract = attribute.ConstructorArguments.Length > 0
                ? attribute.ConstructorArguments[0].Value as string : null;
            contract ??= type.ToDisplayString() + "/v1";
            if (!contracts.Add(contract))
            {
                output.ReportDiagnostic(Diagnostic.Create(Duplicate, type.Locations.FirstOrDefault(), contract));
                continue;
            }
            var error = Validate(type, out var properties, out var constructor);
            if (string.IsNullOrWhiteSpace(contract)) error = "contract names cannot be empty";
            if (error is not null)
            {
                output.ReportDiagnostic(Diagnostic.Create(Unsupported, type.Locations.FirstOrDefault(), type.Name, error));
                continue;
            }
            output.AddSource("OutboxMessage_" + index + ".g.cs", Generate(type, contract, properties, constructor!, index++));
        }
    }

    private static string? Validate(INamedTypeSymbol type, out IPropertySymbol[] properties, out IMethodSymbol? constructor)
    {
        properties = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public).ToArray();
        constructor = null;
        if (type.TypeKind != TypeKind.Class || type.IsAbstract || type.IsGenericType || type.ContainingType is not null
            || type.DeclaredAccessibility != Accessibility.Public)
            return "use a public, non-generic, non-nested concrete partial class or record";
        if (type.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is not TypeDeclarationSyntax declaration
                || !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
            return "all declarations must be partial";
        if (type.BaseType?.SpecialType != SpecialType.System_Object)
            return "message inheritance is not supported";
        if (type.GetMembers().OfType<IFieldSymbol>().Any(f => !f.IsStatic && f.DeclaredAccessibility == Accessibility.Public))
            return "use properties instead of public fields";
        if (HasJsonAttributes(type)) return "custom JSON attributes require an explicit serializer registration";
        foreach (var property in properties)
        {
            if (property.IsIndexer || property.GetMethod?.DeclaredAccessibility != Accessibility.Public)
                return "properties must have public getters and cannot be indexers";
            if (HasJsonAttributes(property)) return $"custom JSON attributes on '{property.Name}' are not supported";
            if (!Supported(property.Type)) return $"property '{property.Name}' has unsupported type '{property.Type}'";
        }
        var members = properties;
        var candidates = type.InstanceConstructors.Where(c => c.DeclaredAccessibility == Accessibility.Public
            && c.Parameters.All(p => p.RefKind == RefKind.None && members.Any(property =>
                string.Equals(property.Name, p.Name, StringComparison.OrdinalIgnoreCase)
                && SymbolEqualityComparer.Default.Equals(property.Type, p.Type)))
            && members.All(p => p.SetMethod?.DeclaredAccessibility == Accessibility.Public
                || c.Parameters.Any(parameter => string.Equals(parameter.Name, p.Name, StringComparison.OrdinalIgnoreCase))))
            .OrderByDescending(c => c.Parameters.Length).ToArray();
        if (candidates.Length == 0) return "a public constructor must map to properties; remaining properties need public set/init accessors";
        if (candidates.Length > 1 && candidates[0].Parameters.Length == candidates[1].Parameters.Length)
            return "constructor selection is ambiguous";
        constructor = candidates[0];
        return null;
    }

    private static bool HasJsonAttributes(ISymbol symbol) => symbol.GetAttributes().Any(a =>
        a.AttributeClass?.ContainingNamespace.ToDisplayString() == "System.Text.Json.Serialization");

    private static ITypeSymbol? Element(ITypeSymbol type)
        => type is IArrayTypeSymbol { Rank: 1 } array ? array.ElementType
            : type is INamedTypeSymbol { IsGenericType: true } list
              && list.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.List<T>" ? list.TypeArguments[0] : null;

    private static ITypeSymbol? NullableElement(ITypeSymbol type)
        => type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            ? named.TypeArguments[0] : null;

    private static bool Supported(ITypeSymbol type)
    {
        if (NullableElement(type) is { } inner) return Supported(inner);
        if (Element(type) is { } element) return Supported(element);
        return type.SpecialType is SpecialType.System_String or SpecialType.System_Boolean
            or SpecialType.System_Byte or SpecialType.System_SByte or SpecialType.System_Int16
            or SpecialType.System_UInt16 or SpecialType.System_Int32 or SpecialType.System_UInt32
            or SpecialType.System_Int64 or SpecialType.System_UInt64 or SpecialType.System_Single
            or SpecialType.System_Double or SpecialType.System_Decimal
            || type.ToDisplayString() is "System.Guid" or "System.DateTime" or "System.DateTimeOffset";
    }

    private static string Generate(INamedTypeSymbol type, string contract, IPropertySymbol[] properties, IMethodSymbol constructor, int index)
    {
        var name = TypeName(type);
        // Include the message namespace/name in the codec name so independent message
        // assemblies can export codecs without producing identical fully qualified names.
        var codec = "OutboxCodec_" + string.Concat(type.ToDisplayString().Select(c => char.IsLetterOrDigit(c) ? c : '_')) + "_" + index;
        var sb = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        sb.AppendLine($"[assembly: global::Stella.Ergosfare.Plugins.Outbox.OutboxCodecManifestAttribute(typeof(global::Stella.Ergosfare.Plugins.Outbox.Generated.{codec}))]");
        sb.AppendLine("namespace Stella.Ergosfare.Plugins.Outbox.Generated;");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"public static class {codec} {{");
        sb.AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine($"public static void Register() => global::Stella.Ergosfare.Plugins.Outbox.GeneratedOutboxMessages.Register<{name}>({Literal(contract)}, Write, Read);");
        sb.AppendLine($"private static byte[] Write({name} message) {{");
        sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine("using var stream = new global::System.IO.MemoryStream();");
        sb.AppendLine("using (var writer = new global::System.Text.Json.Utf8JsonWriter(stream)) {");
        sb.AppendLine("writer.WriteStartObject();");
        var counter = 0;
        foreach (var property in properties)
        {
            sb.AppendLine($"writer.WritePropertyName({Literal(property.Name)});");
            WriteValue(sb, property.Type, "message.@" + property.Name, ref counter);
        }
        sb.AppendLine("writer.WriteEndObject();\n}\nreturn stream.ToArray();\n}");
        sb.AppendLine($"private static {name} Read(byte[] payload) {{");
        sb.AppendLine("using var document = global::System.Text.Json.JsonDocument.Parse(payload);\nvar root = document.RootElement;");
        sb.AppendLine("if (root.ValueKind != global::System.Text.Json.JsonValueKind.Object) throw new global::System.Text.Json.JsonException(\"Expected an outbox message object.\");");
        for (var i = 0; i < properties.Length; i++)
        {
            sb.AppendLine($"var field{i} = root.GetProperty({Literal(properties[i].Name)});");
            sb.AppendLine($"{TypeName(properties[i].Type)} value{i} = {ReadValue(properties[i].Type, "field" + i, ref counter)};");
        }
        var arguments = constructor.Parameters.Select(p => "value" + Array.FindIndex(properties,
            property => string.Equals(property.Name, p.Name, StringComparison.OrdinalIgnoreCase)));
        sb.AppendLine($"return new {name}({string.Join(", ", arguments)}) {{");
        for (var i = 0; i < properties.Length; i++)
            if (properties[i].SetMethod?.DeclaredAccessibility == Accessibility.Public
                && (properties[i].IsRequired || !constructor.Parameters.Any(p =>
                    string.Equals(p.Name, properties[i].Name, StringComparison.OrdinalIgnoreCase))))
                sb.AppendLine($"@{properties[i].Name} = value{i},");
        sb.AppendLine("};\n}\n}");
        return sb.ToString();
    }

    private static void WriteValue(StringBuilder sb, ITypeSymbol type, string expression, ref int counter)
    {
        if (NullableElement(type) is { } inner)
        {
            sb.AppendLine($"if ({expression}.HasValue) {{");
            WriteValue(sb, inner, expression + ".Value", ref counter);
            sb.AppendLine("} else writer.WriteNullValue();");
            return;
        }
        if (Element(type) is { } element)
        {
            var variable = "item" + counter++;
            sb.AppendLine($"if ({expression} is null) writer.WriteNullValue(); else {{ writer.WriteStartArray(); foreach (var {variable} in {expression}) {{");
            WriteValue(sb, element, variable, ref counter);
            sb.AppendLine("} writer.WriteEndArray(); }");
            return;
        }
        var method = type.SpecialType == SpecialType.System_Boolean ? "WriteBooleanValue"
            : type.SpecialType == SpecialType.System_String || type.SpecialType == SpecialType.None
                || type.SpecialType == SpecialType.System_DateTime ? "WriteStringValue" : "WriteNumberValue";
        sb.AppendLine($"writer.{method}({expression});");
    }

    private static string ReadValue(ITypeSymbol type, string expression, ref int counter)
    {
        if (NullableElement(type) is { } inner)
            return $"{expression}.ValueKind == global::System.Text.Json.JsonValueKind.Null ? ({TypeName(type)})null : {ReadValue(inner, expression, ref counter)}";
        if (Element(type) is { } element)
        {
            var variable = "element" + counter++;
            var read = ReadValue(element, variable, ref counter);
            var collection = type is IArrayTypeSymbol ? "ToArray" : "ToList";
            return $"{expression}.ValueKind == global::System.Text.Json.JsonValueKind.Null ? null! : global::System.Linq.Enumerable.{collection}(global::System.Linq.Enumerable.Select<global::System.Text.Json.JsonElement, {TypeName(element)}>({expression}.EnumerateArray(), {variable} => ({TypeName(element)})({read})))";
        }
        var getter = type.SpecialType switch
        {
            SpecialType.System_String => "GetString", SpecialType.System_Boolean => "GetBoolean",
            SpecialType.System_Byte => "GetByte", SpecialType.System_SByte => "GetSByte",
            SpecialType.System_Int16 => "GetInt16", SpecialType.System_UInt16 => "GetUInt16",
            SpecialType.System_Int32 => "GetInt32", SpecialType.System_UInt32 => "GetUInt32",
            SpecialType.System_Int64 => "GetInt64", SpecialType.System_UInt64 => "GetUInt64",
            SpecialType.System_Single => "GetSingle", SpecialType.System_Double => "GetDouble",
            SpecialType.System_Decimal => "GetDecimal", _ => "Get" + type.Name
        };
        return expression + "." + getter + "()" + (type.SpecialType == SpecialType.System_String ? "!" : "");
    }

    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
    private static string Literal(string value) => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, true);
}
