name: readme

on:
  workflow_run: 
    workflows: 
      - Coverage
    branches: 
      - main
    types:
      - completed

permissions:
  contents: write   # <-- give the workflow permission to push commits
jobs:
  GenReadMe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: stellayazilim/protostar@v0.1.40
        id: protostar
        with:
          version: v1.0.0
          template: '.github/templates/readme.md'
          args: |
            --branch ${{ github.ref_name }}
      - name: Write to file
        shell: bash
        run: |
          echo "${{ steps.protostar.outputs.stdout }}" > readme.md
      - name: Commit generated file
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add readme.md
          git commit -m "Update changelog" || echo "No changes to commit"
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          if [ -z "${GITHUB_REF##refs/tags/*}" ]; then
            echo "Running on a tag — skipping commit push"
          else
            git push origin "$BRANCH"
          fi